/*
* பதிப்புரிமை (c) 2012 - தற்போது வரை Adobe Systems Incorporated. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.
*
* இந்த மென்பொருளின் நகல் மற்றும் தொடர்புடைய ஆவணக் கோப்புகளை ("மென்பொருள்") பெறும் எந்தவொரு நபருக்கும் இதன் மூலம் இலவசமாக அனுமதி வழங்கப்படுகிறது,
* கட்டுப்பாடுகள் இல்லாமல் மென்பொருளை கையாள, வரம்புகள் இல்லாமல் உட்பட
* மென்பொருளைப் பயன்படுத்த, நகலெடுக்க, மாற்ற, ஒன்றிணைக்க, வெளியிட, விநியோகிக்க, துணை உரிமம் வழங்க,
* மற்றும்/அல்லது மென்பொருளின் நகல்களை விற்க, மற்றும்
* மென்பொருள் வழங்கப்பட்ட நபர்களுக்கு அவ்வாறு செய்ய அனுமதிக்க, பின்வரும் நிபந்தனைகளுக்கு உட்பட்டு:
*
* மேலே உள்ள பதிப்புரிமை அறிவிப்பு மற்றும் இந்த அனுமதி அறிவிப்பு
* மென்பொருளின் அனைத்து நகல்களிலும் அல்லது கணிசமான பகுதிகளிலும் சேர்க்கப்படும்.
*
* மென்பொருள் எந்த வகையான, வெளிப்படையான அல்லது
* மறைமுகமான, வணிக உத்தரவாதங்களை உள்ளடக்கிய ஆனால் வரம்பிடப்படாத "உள்ளபடியே" வழங்கப்படுகிறது,
* ஒரு குறிப்பிட்ட நோக்கம் மற்றும் மீறலுக்கான பொருத்தம். எந்தவொரு சந்தர்ப்பத்திலும் ஆசிரியர்கள் அல்லது பதிப்புரிமைதாரர்கள் எந்தவொரு உரிமைகோரல், சேதங்கள் அல்லது பிறவற்றிற்கும் பொறுப்பேற்க மாட்டார்கள். * ஒப்பந்தம், குற்றச்செயல் அல்லது வேறுவிதமாக எழும் எந்தவொரு செயலாக இருந்தாலும் சரி, பொறுப்பு. * மென்பொருள் அல்லது பயன்பாடு அல்லது பிறவற்றிலிருந்து, வெளியே அல்லது தொடர்பாக
* மென்பொருளில் உள்ள பரிவர்த்தனைகள்.
* 
*/

define({

    /**
     * பிழைகள் 
     */

    // பொது கோப்பு io பிழை சரங்கள்
    "GENERIC_ERROR" : "(பிழை {0})",
    "NOT_FOUND_ERR" : "கோப்பு அல்லது கோப்பகம் கிடைக்கவில்லை.",
    "NOT_READABLE_ERR" : "கோப்பு அல்லது கோப்பகம் படிக்க முடியாதது.",
    "EXCEEDS_MAX_FILE_SIZE" : "{0} மெபைக்கும் அதிகமான கோப்புகளை {APP_NAME} இல் திறக்க முடியாது.",
    "NO_MODIFICATION_ALLOWED_ERR" : "இலக்கு கோப்பகத்தை மாற்ற முடியாது.",
    "NO_MODIFICATION_ALLOWED_ERR_FILE" : "மாற்றங்களைச் செய்ய உங்களுக்கு அனுமதி இல்லை.",
    "CONTENTS_MODIFIED_ERR" : "கோப்பு {APP_NAME} க்கு வெளியே மாற்றியமைக்கப்பட்டுள்ளது.",
    "UNSUPPORTED_ENCODING_ERR" : "தெரியாத குறியீட்டு வடிவம்,",
    "ENCODE_FILE_FAILED_ERR" : "{APP_NAME} இந்த கோப்பின் உள்ளடக்கங்களை குறியாக்கம் செய்ய முடியவில்லை.",
    "DECODE_FILE_FAILED_ERR" : "{APP_NAME} இந்த கோப்பின் உள்ளடக்கங்களை மறைகுறியாக்கம் செய்ய முடியவில்லை.",
    "UNSUPPORTED_UTF16_ENCODING_ERR" : "{APP_NAME} தற்போது UTF-16 குறியாக்கம் செய்யப்பட்ட கோப்புகளை ஆதரிக்கவில்லை.",
    "FILE_EXISTS_ERR" : "கோப்பு அல்லது கோப்பகம் ஏற்கனவே உள்ளது.",
    "FILE" : "கோப்பு",
    "FILE_TITLE" : "கோப்பு",
    "DIRECTORY" : "அடைவு",
    "DIRECTORY_TITLE" : "அடைவு",
    "DIRECTORY_NAMES_LEDE" : "அடைவு பெயர்கள்",
    "FILENAMES_LEDE" : "கோப்பு பெயர்கள்",
    "FILENAME" : "கோப்பு பெயர்",
    "DIRECTORY_NAME" : "அடைவு பெயர்",

    // திட்டப் பிழை சரங்கள்
    "ERROR_LOADING_PROJECT" : "திட்டத்தை ஏற்றுவதில் பிழை",
    "OPEN_DIALOG_ERROR" : "கோப்பு உரையாடலைத் திறக்கும்போது பிழை ஏற்பட்டது. (பிழை {0}.)",
    "REQUEST_NATIVE_FILE_SYSTEM_ERROR" : "கோப்பைத் திறக்க முயற்சிக்கும்போது பிழை ஏற்பட்டது <span class='dialog-filename'>{0}</span>. (பிழை {1}.)",
    "READ_DIRECTORY_ENTRIES_ERROR" : "கோப்பு உள்ளடக்கங்களைப் படிக்கும்போது பிழை ஏற்பட்டது <span class='dialog-filename'>{0}</span>. (பிழை {1}.)",

    // கோப்பு திறப்பு/சேமிப்பு பிழை சரம்
    "ERROR_OPENING_FILE_TITLE" : "கோப்பைத் திறப்பதில் பிழை",
    "ERROR_OPENING_FILE" : "கோப்பைத் திறப்பதில் பிழை <span> class='dialog-filename'>{0}</span>. {1}",
    "ERROR_OPENING_FILES" : "பின்வரும் கோப்புகளைத் திறக்க முயற்சிக்கும்போது பிழை ஏற்பட்டது:",
    "ERROR_RELOADING_FILE_TITLE" : "வட்டில் இருந்து மாற்றங்களைப் புதுப்பிப்பதில் பிழை",
    "ERROR_RELOADING_FILE" : "கோப்பைப் புதுப்பிக்க முயற்சிக்கும்போது பிழை ஏற்பட்டது <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_SAVING_FILE_TITLE" : "கோப்பைச் சேமிக்கும்போது பிழை",
    "ERROR_SAVING_FILE" : "கோப்பைச் சேமிக்க முயற்சிக்கும்போது பிழை ஏற்பட்டது <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_RENAMING_FILE_TITLE" : "{0} ஐ மறுபெயரிடும்போது பிழை",
    "ERROR_RENAMING_FILE" : "{2} <span class='dialog-filename'>{0}</span> ஐ மறுபெயரிடும்போது பிழை ஏற்பட்டது. {1}",
    "ERROR_RENAMING_NOT_IN_PROJECT" : "கோப்பு அல்லது கோப்பகம் தற்போதைய திட்டத்தின் ஒரு பகுதியாக இல்லை. துரதிர்ஷ்டவசமாக, இந்த நேரத்தில் திட்டக் கோப்புகளை மட்டுமே மறுபெயரிட முடியும்.",
    "ERROR_DELETING_FILE_TITLE" : "{0} ஐ நீக்கும்போது பிழை",
    "ERROR_DELETING_FILE" : "{2} <span class='dialog-filename'>{0}</span> ஐ நீக்க முயற்சிக்கும்போது பிழை ஏற்பட்டது. {1}",
    "INVALID_FILENAME_TITLE" : "தவறான {0}",
    "INVALID_FILENAME_MESSAGE" : "{0} எந்த கணினி ஒதுக்கப்பட்ட சொற்களையும் பயன்படுத்த முடியாது, ஒரு புள்ளியுடன் முடிவடையும் (.), அல்லது பின்வரும் எழுத்துக்களில் ஏதேனும் ஒன்றைப் பயன்படுத்த முடியாது: <code> class='empasized'>{1}</code>",
    "ENTRY_WITH_SAME_NAME_EXISTS" : "<span class='dialog-filename'>{0}</span> என்ற பெயரில் ஒரு கோப்பு அல்லது கோப்பகம் உள்ளது.",
    "ERROR_CREATING_FILE_TITLE" : "{0} ஐ உருவாக்குவதில் பிழை",
    "ERROR_CREATING_FILE" : "{0} <span class='dialog-filename'>{1}</span> ஐ உருவாக்க முயற்சிப்பதில் பிழை. {2}",
    "ERROR_MIXED_DRAGDROP" : "ஒரே நேரத்தில் மற்ற கோப்புகளுடன் கோப்புறையைத் திறக்க முடியாது.",
    
    // பயனர் விசை வரைபட பிழை சரங்கள்
    "ERROR_KEYMAP_TITLE" : "பயனர் விசை வரைபடத்தைப் படிப்பதில் பிழை",
    "ERROR_KEYMAP_CORRUPT" : "உங்கள் விசை வரைபடக் கோப்பில் தவறான JSON குறியீடு உள்ளது. அதன் வடிவமைப்பை நீங்கள் சரிசெய்ய கோப்பு திறக்கும்.",
    "ERROR_LOADING_KEYMAP" : "உங்கள் விசை வரைபடக் கோப்பு UTF-8 குறியாக்கம் செய்யப்படவில்லை அல்லது எளிய உரை வடிவத்தில் இல்லை, எனவே அதை ஏற்ற முடியாது.",
    "ERROR_RESTRICTED_COMMANDS" : "பின்வருபவை கட்டளைகளை மீண்டும் ஒதுக்க முடியாது விசை சேர்க்கைகள்: {0}",
    "ERROR_RESTRICTED_SHORTCUTS" : "பின்வரும் குறுக்குவழி விசைகளை மீண்டும் ஒதுக்க முடியாது: {0}",
    "ERROR_MULTIPLE_SHORTCUTS" : "நீங்கள் பின்வரும் கட்டளைகளுக்கு பல குறுக்குவழிகளை ஒதுக்குகிறீர்கள்: {0}",
    "ERROR_DUPLICATE_SHORTCUTS" : "பின்வரும் குறுக்குவழிகளுக்கு பல குறுக்குவழிகள் உள்ளன: {0}",
    "ERROR_INVALID_SHORTCUTS" : "பின்வரும் குறுக்குவழிகள் தவறானவை: {0}",
    "ERROR_NONEXISTENT_COMMANDS" : "நீங்கள் இல்லாத கட்டளைகளுக்கு குறுக்குவழிகளை ஒதுக்குகிறீர்கள்: {0}",
    
    // பயன்பாட்டு விருப்பத்தேர்வுகள் சிதைக்கின்ற பிழை சரங்கள்
    "ERROR_PREFS_CORRUPT_TITLE" : "விருப்பத்தேர்வுகளைப் படிப்பதில் பிழை",
    "ERROR_PREFS_CORRUPT" : "விருப்பத்தேர்வுகள் கோப்பில் தவறான JSON குறியீடு உள்ளது. கோப்பு திறக்கப்படும், எனவே நீங்கள் அதன் வடிவமைப்பை சரிசெய்ய முடியும். மாற்றங்கள் நடைமுறைக்கு வர {APP_NAME} ஐ மறுதொடக்கம் செய்ய வேண்டும்.",
    "ERROR_PROJ_PREFS_CORRUPT" : "திட்ட அமைப்புகள் கோப்பில் தவறான JSON குறியீடு உள்ளது. அதன் வடிவமைப்பை சரிசெய்ய கோப்பு திறக்கப்படும். மாற்றங்கள் நடைமுறைக்கு வர திட்டத்தை மீண்டும் ஏற்ற வேண்டும்.",
    
    // பயன்பாட்டு பிழை சரங்கள்
    "ERROR_IN_BROWSER_TITLE" : "அச்சச்சோ! {APP_NAME} இன்னும் உலாவியில் வேலை செய்யவில்லை.",
    "ERROR_IN_BROWSER" : "{APP_NAME} HTML இல் எழுதப்பட்டுள்ளது, ஆனால் இப்போது அது ஒரு டெஸ்க்டாப் பயன்பாடாக செயல்படுகிறது, எனவே நீங்கள் அதைக் கொண்டு உள்ளூர் கோப்புகளைத் திருத்தலாம். {APP_NAME} ஐ இயக்க <b>github.com/brackets-cont/brackets-shell</b> மூலத்தில் API ஐப் பயன்படுத்தவும்.",
    
    // ProjectManager max files error string
    "ERROR_MAX_FILES_TITLE" : "பிழை அட்டவணைப்படுத்துதல் கோப்புகள்",
    "ERROR_MAX_FILES" : "இந்த திட்டத்தில் 30,000 க்கும் மேற்பட்ட கோப்புகள் உள்ளன. பல கோப்புகளுக்கு இடையிலான பண்புகள் முடக்கப்படும், அல்லது அவை திட்டம் காலியாக இருப்பது போல் செயல்படும். <a href='https://github.com/brackets-cont/brackets/wiki/Large-Projects'>பெரிய திட்டங்களுடன் பணிபுரிவது பற்றி மேலும் படிக்கவும்</a>.",
    
    // நேரடி முன்னோட்ட பிழை சரங்கள்
    "ERROR_LAUNCHING_BROWSER_TITLE" : "உலாவியைத் தொடங்குவதில் பிழை",
    "ERROR_CANT_FIND_CHROME" : "Google Chrome \u2011 உலாவியைக் கண்டுபிடிக்க முடியவில்லை. அது நிறுவப்பட்டதா என்பதை உறுதிப்படுத்தவும்.",
    "ERROR_LAUNCHING_BROWSER" : "உலாவியைத் தொடங்குவதில் தோல்வி. (பிழை {0}.)",
    
    "LIVE_DEVELOPMENT_ERROR_TITLE" : "முன்னோட்டம் பிழை",
    "LIVE_DEVELOPMENT_RELAUNCH_TITLE" : "உலாவியுடன் இணைக்கிறது",
    "LIVE_DEVELOPMENT_ERROR_MESSAGE" : "முன்னோட்டம் இணைக்க, தொலைநிலை பிழைத்திருத்தத்தை இயக்கிய நிலையில் Chrome ஐ மறுதொடக்கம் செய்ய வேண்டும்.<br /><br />Chrome ஐ மறுதொடக்கம் செய்து தொலைநிலை பிழைத்திருத்தத்தை இயக்கவா?<br /><br />",
    "LIVE_DEV_LOADING_ERROR_MESSAGE" : "முன்னோட்டம் பக்கத்தை ஏற்ற முடியவில்லை.",
    "LIVE_DEV_NEED_HTML_MESSAGE" : "ஒரு HTML கோப்பைத் திறக்கவும் அல்லது முன்னோட்டத்தைத் தொடங்க திட்டத்தில் ஒரு index.html கோப்பு இருப்பதை உறுதிசெய்யவும்.",
    "LIVE_DEV_NEED_BASEURL_MESSAGE" : "ஒரு சேவையகக் கோப்போடு முன்னோட்டத்தைத் தொடங்க, இந்த திட்டத்திற்கான URL குறிப்பிடப்பட வேண்டும்.",
    "LIVE_DEV_SERVER_NOT_READY_MESSAGE" : "முன்னோட்டம் கோப்புகளுக்கான HTTP சேவையகத்தைத் தொடங்குவதில் பிழை. முயற்சிக்கவும். மீண்டும்.",
    "LIVE_DEV_INFO_TITLE" : "முன்னோட்டத்திற்கு வரவேற்கிறோம்!",
    "LIVE_DEV_INFO_MESSAGE" : "முன்னோட்டம் {APP_NAME} ஐ உங்கள் உலாவியுடன் இணைக்கிறது. இது உலாவியில் திறக்கிறது, நீங்கள் குறியீட்டைத் திருத்தும்போது உடனடியாகப் புதுப்பிக்கப்படும் HTML கோப்பின் முன்னோட்டம்.<br /><br />{APP_NAME} இன் இந்த ஆரம்ப பதிப்பில், முன்னோட்டம் <strong>Google Chrome</strong> இல் மட்டுமே செயல்படும், மேலும் நீங்கள் <strong>CSS அல்லது HTML கோப்புகளைத் திருத்தும்போது</strong> உடனடியாகப் புதுப்பிக்கப்படும். JavaScript கோப்புகளில் ஏற்படும் மாற்றங்கள் சேமிக்கப்படும்போது புதுப்பிக்கப்படும்.<br /><br />(இந்தச் செய்தி ஒரு முறை மட்டுமே தோன்றும்.)",
    "LIVE_DEVELOPMENT_TROUBLESHOOTING" : "மேலும் தகவலுக்கு, <a href='{0}' title='{0}'>நேரடி முன்னோட்ட இணைப்பு பிழைகளைச் சரிசெய்தல்</a> என்பதைப் பார்க்கவும்.",
    
    "LIVE_DEV_STATUS_TIP_NOT_CONNECTED" : "முன்னோட்டம்",
    "LIVE_DEV_STATUS_TIP_PROGRESS1" : "முன்னோட்டம்: இணைக்கிறது\u2026",
    "LIVE_DEV_STATUS_TIP_PROGRESS2" : "முன்னோட்டம்: துவக்குகிறது\u2026",
    "LIVE_DEV_STATUS_TIP_CONNECTED" : "முன்னோட்டம் முடி",
    "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC" : "முன்னோட்டம் (புதுப்பிக்க கோப்பைச் சேமிக்கவும்)",
    "LIVE_DEV_STATUS_TIP_SYNC_ERROR" : "முன்னோட்டம் (தொடரியல் பிழை காரணமாக புதுப்பிக்கப்படவில்லை)",
    
    "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS" : "உலாவி மேம்பாட்டு கருவிகள் திறக்கப்பட்டதால் முன்னோட்டம் ரத்து செய்யப்பட்டது",
    "LIVE_DEV_DETACHED_TARGET_CLOSED" : "உலாவியில் பக்கம் மூடப்பட்டதால் முன்னோட்டம் ரத்து செய்யப்பட்டது",
    "LIVE_DEV_NAVIGATED_AWAY" : "தற்போதைய திட்டத்தில் இல்லாத பக்கத்திற்கு உலாவி சென்றதால் முன்னோட்டம் ரத்து செய்யப்பட்டது",
    "LIVE_DEV_CLOSED_UNKNOWN_REASON" : "தெரியாத காரணத்திற்காக முன்னோட்டம் ரத்து செய்யப்பட்டது ({0})",
    
    "SAVE_CLOSE_TITLE" : "மாற்றங்களைச் சேமி",
    "SAVE_CLOSE_MESSAGE" : "ஆவணத்தில் செய்யப்பட்ட மாற்றங்களைச் சேமிக்க விரும்புகிறீர்களா <span class='dialog-filename'>{0}</span>?",
    "SAVE_CLOSE_MULTI_MESSAGE" : "பின்வரும் கோப்புகளில் மாற்றங்களைச் சேமிக்க விரும்புகிறீர்களா?",
    "EXT_MODIFIED_TITLE" : "வெளிப்புற மாற்றங்கள்",
    "CONFIRM_DELETE_TITLE" : "நீக்குவதை உறுதிப்படுத்து",
    "CONFIRM_FILE_DELETE" : "கோப்பை நீக்க விரும்புகிறீர்களா <span class='dialog-filename'>{0}</span>?",
    "CONFIRM_FOLDER_DELETE" : "கோப்புறையை நீக்க விரும்புகிறீர்களா <span class='dialog-filename'>{0}</span>?",
    "FILE_DELETED_TITLE" : "கோப்பு நீக்கப்பட்டது",
    "EXT_MODIFIED_WARNING" : "<span class='dialog-filename'>{0}</span> {APP_NAME} க்கு வெளியே உள்ள வட்டில் மாற்றியமைக்கப்பட்டுள்ளது.<br /><br />கோப்பைச் சேமித்து அந்த மாற்றங்களை மேலெழுத விரும்புகிறீர்களா? மாற்றங்கள்?",
    "EXT_MODIFIED_MESSAGE" : "<span class='dialog-filename'>{0}</span> {APP_NAME} க்கு வெளியே உள்ள வட்டில் மாற்றப்பட்டுள்ளது, ஆனால் அது {APP_NAME} இல் சேமிக்கப்படாத மாற்றங்களையும் கொண்டுள்ளது.<br /><br />நீங்கள் எந்த பதிப்பை வைத்திருக்க விரும்புகிறீர்கள்?",
    "EXT_DELETED_MESSAGE" : "<span class='dialog-filename'>{0}</span> {APP_NAME} க்கு வெளியே உள்ள வட்டில் நீக்கப்பட்டுள்ளது, ஆனால் அது {APP_NAME} இல் சேமிக்கப்படாத மாற்றங்களையும் கொண்டுள்ளது.<br /><br />உங்கள் மாற்றங்களை வைத்திருக்க விரும்புகிறீர்களா?",
    
    // பொதுவான உரையாடல்/பொத்தான் லேபிள்கள்
    "முடிந்தது" : "முடிந்தது",
    "சரி" : "சரி",
    "ரத்துசெய்" : "ரத்துசெய்",
    "DONT_SAVE" : "சேமிக்காதே",
    "சேமி" : "சேமி",
    "SAVE_AS" : "இவ்வாறு சேமி\u2026",
    "SAVE_AND_OVERWRITE" : "மேலெழுது",
    "DELETE" : "நீக்கு",
    "BUTTON_YES" : "ஆம்",
    "BUTTON_NO" : "இல்லை",

    // கோப்புகளில் கண்டுபிடி, மாற்றவும், கண்டுபிடி
    "FIND_MATCH_INDEX" : "{0} / {1}",
    "FIND_NO_RESULTS" : "முடிவுகள் இல்லை",
    "FIND_QUERY_PLACEHOLDER" : "தேடல்\u2026",
    "FIND_HISTORY_MAX_COUNT" : "தேடல் வரலாற்றில் அதிகபட்ச உருப்படிகளின் எண்ணிக்கை",
    "REPLACE_PLACEHOLDER" : "சரத்துடன் மாற்றவும்\u2026",
    "BUTTON_REPLACE_ALL" : "அனைத்தையும் மாற்றவும்",
    "BUTTON_REPLACE_BATCH" : "தொகுதியில் மாற்றவும்\u2026",
    "BUTTON_REPLACE_ALL_IN_FILES" : "மாற்று\u2026",
    "BUTTON_REPLACE" : "மாற்று",
    "BUTTON_NEXT" : "\u25B6",
    "BUTTON_PREV" : "\u25C0",
    "BUTTON_NEXT_HINT" : "அடுத்த பொருத்தம்",
    "BUTTON_PREV_HINT" : "முந்தைய பொருத்தம்",
    "BUTTON_CASESENSITIVE_HINT" : "வழக்கு-உணர்திறன்",
    "BUTTON_REGEXP_HINT" : "வழக்கு வெளிப்பாடு",
    "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "செயல்தவிர்க்காமல் மாற்றவும்",
    "REPLACE_WITHOUT_UNDO_WARNING" : "{0} க்கும் மேற்பட்ட கோப்புகளை மாற்ற வேண்டியிருப்பதால், {APP_NAME} வட்டில் திறக்கப்படாத கோப்புகளை மாற்றியமைக்கிறது.<br />இந்த கோப்புகளில் உள்ள மாற்றங்களை நீங்கள் செயல்தவிர்க்க முடியாது.",
    "BUTTON_REPLACE_WITHOUT_UNDO" : "செயல்தவிர்க்காமல் மாற்றவும்",
    
    "OPEN_FILE" : "திற கோப்பு",
    "SAVE_FILE_AS" : "கோப்பைச் சேமி",
    "CHOOSE_FOLDER" : "கோப்புறையைத் தேர்வுசெய்க",
    
    "RELEASE_NOTES" : "குறிப்புகளை வெளியிடு",
    "NO_UPDATE_TITLE" : "நீங்கள் புதுப்பித்த நிலையில் இருக்கிறீர்கள்!",
    "NO_UPDATE_MESSAGE" : "நீங்கள் {APP_NAME} இன் சமீபத்திய பதிப்பைப் பயன்படுத்துகிறீர்கள்.",
    
    // கண்டுபிடித்து மாற்றவும்
    "FIND_REPLACE_TITLE_LABEL" : "மாற்றவும்",
    "FIND_REPLACE_TITLE_WITH" : "with",
    "FIND_TITLE_LABEL" : "கண்டுபிடிக்கப்பட்டது",
    "FIND_TITLE_SUMMARY" : "&mdash; {0} {1} {2} {3}",
    
    // கோப்புகளில் கண்டுபிடி
    "FIND_NUM_FILES" : "{0} {1}",
    "FIND_IN_FILES_SCOPED" : "from <span> class='dialog-filename'>{0}</span>",
    "FIND_IN_FILES_NO_SCOPE" : "திட்டத்தில்",
    "FIND_IN_FILES_ZERO_FILES" : "வடிகட்டி அனைத்து கோப்புகளையும் புறக்கணிக்கிறது {0}",
    "FIND_IN_FILES_FILE" : "கோப்பில்",
    "FIND_IN_FILES_FILES" : "கோப்பில்",
    "FIND_IN_FILES_MATCH" : "பொருத்தம்",
    "FIND_IN_FILES_MATCHES" : "பொருத்தம்",
    "FIND_IN_FILES_MORE_THAN" : "மேலும்",
    "FIND_IN_FILES_PAGING" : "{0}&ndash;{1}",
    "FIND_IN_FILES_FILE_PATH" : "<span class='dialog-filename'>{0}</span> {2} <span> class='dialog-path'>{1}</span>", // விண்டோஸில் em dash eventually க்குப் பதிலாக சாதாரண கோடுகளைப் பயன்படுத்த வேண்டும்
    "FIND_IN_FILES_EXPAND_COLLAPSE" : "அனைத்தையும் விரிவாக்க அல்லது சுருக்க Ctrl/Cmd",
    "FIND_IN_FILES_INDEXING" : "விரைவான தேடலுக்கான அட்டவணைப்படுத்தல்\u2026",
    "REPLACE_IN_FILES_ERRORS_TITLE" : "மாற்று பிழைகள்",
    "REPLACE_IN_FILES_ERRORS" : "பின்வரும் கோப்புகள் மீட்டெடுப்பிலிருந்து மாறிவிட்டதால் அல்லது எழுத முடியாததால் அவை மாற்றப்படவில்லை.",
    
    "ERROR_FETCHING_UPDATE_INFO_TITLE" : "புதுப்பிப்புத் தகவலை மீட்டெடுப்பதில் பிழை",
    "ERROR_FETCHING_UPDATE_INFO_MSG" : "சேவையகத்திலிருந்து சமீபத்திய புதுப்பிப்புத் தகவலை மீட்டெடுப்பதில் சிக்கல் ஏற்பட்டது. நீங்கள் பிணையத்துடன் இணைக்கப்பட்டுள்ளீர்கள் என்பதை உறுதிசெய்து மீண்டும் முயற்சிக்கவும்.",
    
    // கோப்பு விலக்கு வடிப்பான்கள்
    "NEW_FILE_FILTER" : "புதிய விலக்கு தொகுப்பு\u2026",
    "CLEAR_FILE_FILTER" : "கோப்புகளை விலக்க வேண்டாம்",
    "NO_FILE_FILTER" : "கோப்புகள் எதுவும் விலக்கப்படவில்லை",
    "EXCLUDE_FILE_FILTER" : "{0} விலக்கு",
    "EDIT_FILE_FILTER" : "திருத்து\u2026",
    "FILE_FILTER_DIALOG" : "தவிர்ப்பு தொகுப்பைத் திருத்து",
    "FILE_FILTER_INSTRUCTIONS" : "பின்வரும் சரங்கள் அல்லது துணை சரங்களுடன் பொருந்தக்கூடிய கோப்புகள் மற்றும் கோப்புறைகளைப் புறக்கணிக்கவும். நீங்கள் <a href='{0}' title='{0}'>வைல்டு கார்டுகளைப்</a> பயன்படுத்தலாம். ஒவ்வொரு சரத்தையும் ஒரு புதிய வரியில் எழுதவும்.",
    "FILTER_NAME_PLACEHOLDER" : "இந்தத் தவிர்ப்புத் தொகுப்பிற்கு பெயரிடுங்கள் (விரும்பினால்)",
    "FILTER_NAME_REMAINING" : "{0} எழுத்துகள் மீதமுள்ளன",
    "FILE_FILTER_CLIPPED_SUFFIX" : "மேலும் {0}",
    "FILTER_COUNTING_FILES" : "கோப்புகளை எண்ணுதல்\u2026",
    "FILTER_FILE_COUNT" : "மொத்தம் {0} கோப்புகளை அனுமதிக்கிறது {1}",
    "FILTER_FILE_COUNT_ALL" : "அனைத்து {0} கோப்புகளையும் அனுமதிக்கிறது {1}",
    
    // விரைவுத் திருத்தம்
    "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND" : "தற்போதைய கர்சர் நிலைக்கு விரைவுத் திருத்தம் கிடைக்கவில்லை",
    "ERROR_CSSQUICKEDIT_BETWEENCLASSES" : "CSS விரைவுத் திருத்தம்: ஒற்றை வகுப்பு பெயர்களுக்கு இடையில் கர்சரை வைக்கவும்",
    "ERROR_CSSQUICKEDIT_CLASSNOTFOUND" : "CSS விரைவுத் திருத்தம்: வகுப்பு பண்புக்கூறு இல்லை",
    "ERROR_CSSQUICKEDIT_IDNOTFOUND" : "CSS விரைவுத் திருத்தம்: ஐடி பண்புக்கூறு இல்லை",
    "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR" : "CSS விரைவுத் திருத்தம்: குறிச்சொல் அல்லது வகுப்பு அல்லது ஐடி பண்புக்கூறில் கர்சரை வைக்கவும்",
    "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX" : "CSS நேர விரைவுத் திருத்தம்: தவறான தொடரியல்",
    "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND" : "JS விரைவுத் திருத்தம்: செயல்பாட்டு பெயரில் கர்சரை வைக்கவும்",
    
    // விரைவு ஆவணங்கள்
    "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND" : "தற்போதைய கர்சர் நிலைக்கு விரைவு ஆவணங்கள் கிடைக்கவில்லை",
    
    /**
    * திட்ட மேலாளர்
    */
    "PROJECT_LOADING" : "ஏற்றுகிறது\u2026",
    "UNTITLED" : "தலைப்பு இல்லாதது",
    "WORKING_FILES" : "வேலை செய்யும் கோப்புகள்",
    
    /**
    * MainViewManager
    */
    "TOP" : "top",
    "BOTTOM" : "கீழ்",
    "இடது" : "இடது ",
    "வலது" : "வலது",
    
    "CMD_SPLITVIEW_NONE" : "பிரிவு இல்லை",
    "CMD_SPLITVIEW_VERTICAL" : "செங்குத்தாகப் பிரிக்கவும்",
    "CMD_SPLITVIEW_HORIZONTAL" : "கிடைமட்டமாகப் பிரிக்கவும்",
    "SPLITVIEW_MENU_TOOLTIP" : "எடிட்டரை செங்குத்தாக அல்லது கிடைமட்டமாகப் பிரிக்கவும்",
    "GEAR_MENU_TOOLTIP" : "பணிப் பட்டியலை அமைக்கவும்",
    
    "SPLITVIEW_INFO_TITLE" : "ஏற்கனவே திறந்திருக்கும்",
    "SPLITVIEW_MULTIPANE_WARNING" : "கோப்பு ஏற்கனவே மற்றொரு பலகத்தில் திறக்கப்பட்டுள்ளது. {APP_NAME} விரைவில் ஒரே கோப்பை பல பலகங்களில் திறப்பதை ஆதரிக்கும். அதுவரை, கோப்பு ஏற்கனவே திறந்திருக்கும் பலகத்தில் காட்டப்படும்.<br /><br />(இந்தச் செய்தி ஒரு முறை மட்டுமே தோன்றும்.)",
    
    /**
    * விசைப்பலகை மாற்றிகள் மற்றும் சிறப்பு விசைப் பெயர்கள்
    */
    "KEYBOARD_CTRL" : "Ctrl",
    "KEYBOARD_SHIFT" : "Shift",
    "KEYBOARD_SPACE" : "Space",
    "KEYBOARD_PAGE_UP" : "Page Up",
    "KEYBOARD_PAGE_DOWN" : "Page Down",
    "KEYBOARD_HOME" : "Home",
    "KEYBOARD_END" : "End",
    "KEYBOARD_INSERT" : "Insert",
    "KEYBOARD_DELETE" : "Delete",
    
    /**
    * StatusBar சரங்கள்
    */
    "STATUSBAR_CURSOR_POSITION" : "வரிசை {0}, நெடுவரிசை {1}",
    "STATUSBAR_SELECTION_CH_SINGULAR" : " \u2014 தேர்ந்தெடுக்கப்பட்டது {0} நெடுவரிசை",
    "STATUSBAR_SELECTION_CH_PLURAL" : " \u2014 தேர்ந்தெடுக்கப்பட்டது {0} நெடுவரிசைகள்",
    "STATUSBAR_SELECTION_LINE_SINGULAR" : " \u2014 தேர்ந்தெடுக்கப்பட்ட {0} வரி",
    "STATUSBAR_SELECTION_LINE_PLURAL" : " \u2014 தேர்ந்தெடுக்கப்பட்ட {0} வரிகள்",
    "STATUSBAR_SELECTION_MULTIPLE" : " \u2014 {0} தேர்வுகள்",
    "STATUSBAR_INDENT_TOOLTIP_SPACES" : "இன்டெண்டேஷனை இடைவெளிகளாக மாற்ற கிளிக் செய்யவும்",
    "STATUSBAR_INDENT_TOOLTIP_TABS" : "இன்டெண்டேஷனை தாவல்களாக மாற்ற கிளிக் செய்யவும்",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES" : "இன்டெண்டேஷனாகப் பயன்படுத்தப்படும் இடைவெளிகளின் எண்ணிக்கையை மாற்ற கிளிக் செய்யவும்",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS" : "தாவலின் அகலத்தை மாற்ற கிளிக் செய்யவும்",
    "STATUSBAR_SPACES" : "இடைவெளிகள்:",
    "STATUSBAR_TAB_SIZE" : "தாவல் அளவு:",
    "STATUSBAR_LINE_COUNT_SINGULAR" : "\u2014 {0} வரி",
    "STATUSBAR_LINE_COUNT_PLURAL" : "\u2014 {0} வரிகள்",
    "STATUSBAR_USER_EXTENSIONS_DISABLED" : "நீட்டிப்புகள் முடக்கப்பட்டன",
    "STATUSBAR_INSERT" : "INS",
    "STATUSBAR_OVERWRITE" : "OVR",
    "STATUSBAR_INSOVR_TOOLTIP" : "செருகல் (INS) மற்றும் மேலெழுதும் (OVR) முறைகளுக்கு இடையில் மாற கிளிக் செய்யவும்",
    "STATUSBAR_LANG_TOOLTIP" : "கோப்பு வகையை மாற்ற கிளிக் செய்யவும்",
    "STATUSBAR_CODE_INSPECTION_TOOLTIP" : "{0}. அறிக்கையைக் காட்ட அல்லது மறைக்க கிளிக் செய்யவும். குழு.",
    "STATUSBAR_DEFAULT_LANG" : "(இயல்புநிலை)",
    "STATUSBAR_SET_DEFAULT_LANG" : ".{0} கோப்புகளுக்கு இயல்புநிலையை அமைக்கவும்",
    "STATUSBAR_ENCODING_TOOLTIP" : "குறியாக்கத்தைத் தேர்ந்தெடு",
    
    // கோட் இன்ஸ்பெக்ஷன்: பிழைகள்/எச்சரிக்கைகள்
    "ERRORS_PANEL_TITLE_MULTIPLE" : "{0} சிக்கல்கள்",
    "SINGLE_ERROR" : "1 {0} சிக்கல்",
    "MULTIPLE_ERRORS" : "{1} {0} சிக்கல்கள்",
    "NO_ERRORS" : "{0} சிக்கல்கள் காணப்படவில்லை \u2013 நல்ல வேலை!",
    "NO_ERRORS_MULTIPLE_PROVIDER" : "எந்த பிரச்சனையும் காணப்படவில்லை \u2013 நல்ல வேலை!",
    "LINT_DISABLED" : "சரிபார்த்தல் முடக்கப்பட்டுள்ளது",
    "NO_LINT_AVAILABLE" : "{0} க்கு சரிபார்த்தல் கிடைக்கவில்லை",
    "NOTHING_TO_LINT" : "சரிபார்க்க எதுவும் இல்லை",
    "LINTER_TIMED_OUT" : "{0} {1} ms காத்திருந்த பிறகு நேரம் முடிந்தது",
    "LINTER_FAILED" : "{0} பிழையுடன் ரத்து செய்யப்பட்டது: {1}",
    
    /**
    * கட்டளை பெயர் மாறிலிகள்
    */
    
    // கோப்பு மெனு கட்டளைகள்
    "FILE_MENU" : "கோப்பு",
    "CMD_FILE_NEW_UNTITLED" : "புதியது",
    "CMD_FILE_NEW" : "புதிய கோப்பு",
    "CMD_FILE_NEW_FOLDER" : "புதிய கோப்பு",
    "CMD_FILE_OPEN" : "திற\u2026",
    "CMD_RECENT_FILES_OPEN" : "சமீபத்தியதைத் திற\u2026",
    "CMD_ADD_TO_WORKING_SET" : "செயல்பாட்டுத் தொகுப்பிற்குத் திற",
    "CMD_OPEN_DROPPED_FILES" : "கைவிடப்பட்ட கோப்புகளைத் திற",
    "CMD_OPEN_FOLDER" : "கோப்புறையைத் திற\u2026",
    "CMD_FILE_CLOSE" : "மூடு",
    "CMD_FILE_CLOSE_ALL" : "மூடு அனைத்தும்",
    "CMD_FILE_CLOSE_LIST" : "பட்டியலை மூடு",
    "CMD_FILE_CLOSE_OTHERS" : "மற்றவற்றை மூடு",
    "CMD_FILE_CLOSE_ABOVE" : "மேலே உள்ளவற்றை மூடு",
    "CMD_FILE_CLOSE_BELOW" : "மற்றவற்றை கீழே மூடு",
    "CMD_FILE_SAVE" : "சேமி",
    "CMD_FILE_SAVE_ALL" : "அனைத்தையும் சேமி",
    "CMD_FILE_SAVE_AS" : "இவ்வாறு சேமி\u2026",
    "CMD_LIVE_FILE_PREVIEW" : "முன்னோட்டம்",
    "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE" : "பரிசோதனை முன்னோட்டத்தை இயக்கு",
    "CMD_RELOAD_LIVE_PREVIEW" : "முன்னோட்டம் புதுப்பிப்பை கட்டாயப்படுத்து",
    "CMD_PROJECT_SETTINGS" : "திட்டம் அமைப்புகள்\u2026",
    "CMD_FILE_RENAME" : "மறுபெயரிடு",
    "CMD_FILE_DELETE" : "நீக்கு",
    "CMD_INSTALL_EXTENSION" : "நீட்டிப்பை நிறுவு\u2026",
    "CMD_EXTENSION_MANAGER" : "நீட்டிப்பு மேலாளர்\u2026",
    "CMD_FILE_REFRESH" : "கோப்பு மரத்தைப் புதுப்பிக்கவும்",
    "CMD_QUIT" : "வெளியேறு",
    // விண்டோஸில் உள்ள சொந்த கோப்பு மெனுவில் பயன்படுத்தப்பட்டது
    "CMD_EXIT" : "வெளியேறு",
    
    // மெனு கட்டளைகளைத் திருத்து
    "EDIT_MENU" : "திருத்து",
    "CMD_UNDO" : "செயல்தவிர்",
    "CMD_REDO" : "மீண்டும் செய்",
    "CMD_CUT" : "வெட்டு",
    "CMD_COPY" : "நகலெடு",
    "CMD_PASTE" : "ஒட்டு",
    "CMD_SELECT_ALL" : "அனைத்தையும் தேர்ந்தெடு",
    "CMD_SELECT_LINE" : "வரியைத் தேர்ந்தெடு",
    "CMD_SPLIT_SEL_INTO_LINES" : "தேர்வை வரிகளாகப் பிரிக்கவும்",
    "CMD_ADD_CUR_TO_NEXT_LINE" : "அடுத்த வரியில் கர்சரைச் சேர்க்கவும்",
    "CMD_ADD_CUR_TO_PREV_LINE" : "முந்தைய வரியில் கர்சரைச் சேர்க்கவும்",
    "CMD_INDENT" : "இன்டென்ட்",
    "CMD_UNINDENT" : "இன்டென்ட் அகற்று",
    "CMD_DUPLICATE" : "நகல்",
    "CMD_DELETE_LINES" : "வரி நீக்கு",
    "CMD_COMMENT" : "கருத்து வரிக்கு மாற்று",
    "CMD_BLOCK_COMMENT" : "கருத்து தொகுதிக்கு மாற்று",
    "CMD_LINE_UP" : "வரி நகர்த்து மேல்",
    "CMD_LINE_DOWN" : "கோட்டை கீழே நகர்த்து",
    "CMD_OPEN_LINE_ABOVE" : "மேலே வரியைத் திற",
    "CMD_OPEN_LINE_BELOW" : "கீழே வரியைத் திற",
    "CMD_TOGGLE_CLOSE_BRACKETS" : "தானாக மூடு",
    "CMD_SHOW_CODE_HINTS" : "குறியீட்டு குறிப்புகளைக் காட்டு",

    // தேடல் மெனு கட்டளைகள்
    "FIND_MENU" : "கண்டுபிடி",
    "CMD_FIND" : "கண்டுபிடி",
    "CMD_FIND_NEXT" : "அடுத்ததைக் கண்டுபிடி",
    "CMD_FIND_PREVIOUS" : "முந்தையதைக் கண்டுபிடி",
    "CMD_FIND_ALL_AND_SELECT" : "அனைத்தையும் கண்டுபிடித்து தேர்ந்தெடுக்கவும்",
    "CMD_ADD_NEXT_MATCH" : "தேர்வில் அடுத்த பொருத்தத்தைச் சேர்க்கவும்",
    "CMD_SKIP_CURRENT_MATCH" : "அடுத்த பொருத்தத்தைத் தவிர்த்து சேர்க்கவும்",
    "CMD_FIND_IN_FILES" : "கோப்புகளில் கண்டுபிடி",
    "CMD_FIND_IN_SUBTREE" : "\u2026",
    "CMD_REPLACE" : "மாற்றவும்",
    "CMD_REPLACE_IN_FILES" : "கோப்புகளில் மாற்றவும்",
    "CMD_REPLACE_IN_SUBTREE" : "இதில் மாற்றவும்\u2026",
    
    // மெனு கட்டளைகளைக் காண்க
    "VIEW_MENU" : "காண்க",
    "CMD_HIDE_SIDEBAR" : "பக்கப்பட்டியை மறை",
    "CMD_SHOW_SIDEBAR" : "பக்கப்பட்டியைக் காட்டு",
    "CMD_TOGGLE_SIDEBAR" : "பக்கப்பட்டியைக் காட்டு அல்லது மறை",
    "CMD_TOGGLE_PANELS" : "பலகங்களைக் காட்டு அல்லது மறை",
    "CMD_TOGGLE_PURE_CODE" : "கவனச்சிதறல்கள் இல்லை",
    "CMD_INCREASE_FONT_SIZE" : "எழுத்துரு அளவை அதிகரிக்கவும்",
    "CMD_DECREASE_FONT_SIZE" : "எழுத்துரு அளவைக் குறைக்கவும்",
    "CMD_RESTORE_FONT_SIZE" : "எழுத்துரு அளவை மீட்டமை",
    "CMD_SCROLL_LINE_UP" : "வரிசையை உருட்டவும்",
    "CMD_SCROLL_LINE_DOWN" : "கோட்டை கீழே உருட்டு",
    "CMD_TOGGLE_LINE_NUMBERS" : "வரி எண்கள்",
    "CMD_TOGGLE_ACTIVE_LINE" : "தேர்ந்தெடுக்கப்பட்ட வரியை முன்னிலைப்படுத்து",
    "CMD_TOGGLE_WORD_WRAP" : "தானியங்கி-மடிப்பு",
    "CMD_LIVE_HIGHLIGHT" : "முன்னோட்டம் சிறப்பம்சமாக",
    "CMD_VIEW_TOGGLE_INSPECTION" : "சேமிக்கும் போது கோப்புகளை ஆய்வு செய்",
    "CMD_WORKINGSET_SORT_BY_ADDED" : "சேர்க்கப்பட்ட நேரத்தின்படி வரிசைப்படுத்து",
    "CMD_WORKINGSET_SORT_BY_NAME" : "பெயரின்படி வரிசைப்படுத்து",
    "CMD_WORKINGSET_SORT_BY_TYPE" : "வகையின்படி வரிசைப்படுத்து",
    "CMD_WORKING_SORT_TOGGLE_AUTO" : "தானியங்கி-வரிசைப்படுத்து",
    "CMD_THEMES" : "தீம்கள்\u2026",
    
    // மெனு கட்டளைகளை வழிநடத்தவும்
    "NAVIGATE_MENU" : "வழிசெலுத்து",
    "CMD_QUICK_OPEN" : "விரைவு திற",
    "CMD_GOTO_LINE" : "வரிக்குச் செல்",
    "CMD_GOTO_DEFINITION" : "விரைவு தேடல் வரையறை",
    "CMD_GOTO_FIRST_PROBLEM" : "முதல் சிக்கலுக்குச் செல்",
    "CMD_TOGGLE_QUICK_EDIT" : "விரைவுத் திருத்தம்",
    "CMD_TOGGLE_QUICK_DOCS" : "விரைவு ஆவணப்படுத்தல்",
    "CMD_QUICK_EDIT_PREV_MATCH" : "முந்தைய பொருத்தம்",
    "CMD_QUICK_EDIT_NEXT_MATCH" : "அடுத்த பொருத்தம்",
    "CMD_CSS_QUICK_EDIT_NEW_RULE" : "புதிய விதி",
    "CMD_NEXT_DOC" : "அடுத்து ஆவணம்",
    "CMD_PREV_DOC" : "முந்தைய ஆவணம்",
    "CMD_NAVIGATE_BACKWARD" : "பின்னோக்கிச் செல்லவும்",
    "CMD_NAVIGATE_FORWARD" : "முன்னோக்கி நகர்த்து",
    "CMD_NEXT_DOC_LIST_ORDER" : "பட்டியலில் அடுத்த ஆவணம்",
    "CMD_PREV_DOC_LIST_ORDER" : "பட்டியலில் முந்தைய ஆவணம்",
    "CMD_SHOW_IN_TREE" : "கோப்பு மரத்தில் காட்டு",
    "CMD_SHOW_IN_EXPLORER" : "எக்ஸ்ப்ளோரரில் காட்டு",
    "CMD_SHOW_IN_FINDER" : "கண்டுபிடிப்பானில் காட்டு",
    "CMD_SHOW_IN_OS" : "இயக்க முறைமையில் காட்டு",
    "CMD_SWITCH_PANE_FOCUS" : "பேன் ஃபோகஸை மாற்று",
    
    // உதவி மெனு கட்டளைகள்
    "HELP_MENU" : "உதவி",
    "CMD_CHECK_FOR_UPDATE" : "புதுப்பிப்புகளைச் சரிபார்க்கவும்",
    "CMD_HOW_TO_USE_BRACKETS" : "{APP_NAME} ஐ எவ்வாறு பயன்படுத்துவது",
    "CMD_SUPPORT" : "{APP_NAME} ஆதரவு",
    "CMD_SUGGEST" : "ஒரு அம்சத்தை பரிந்துரைக்கவும்",
    "CMD_RELEASE_NOTES" : "வெளியீட்டு குறிப்புகள்",
    "CMD_GET_INVOLVED" : "ஈடுபடுங்கள்",
    "CMD_SHOW_EXTENSIONS_FOLDER" : "நீட்டிப்புகள் கோப்புறையைக் காட்டு",
    "CMD_HEALTH_DATA_STATISTICS" : "சுகாதார அறிக்கை",
    "CMD_HOMEPAGE" : "{APP_TITLE} முகப்புப் பக்கம்",
    "CMD_TWITTER" : "ட்விட்டரில் {TWITTER_NAME}",
    "CMD_ABOUT" : "பற்றி {APP_TITLE}",
    "CMD_OPEN_PREFERENCES" : "விருப்பத்தேர்வுகள் கோப்பைத் திற",
    "CMD_OPEN_KEYMAP" : "பயனர் விசைவரைபடத்தைத் திற",
    
    // main-view.html க்கான சரங்கள்
    "EXPERIMENTAL_BUILD" : "பரிசோதனை உருவாக்கம்",
    "RELEASE_BUILD" : "உருவாக்கு",
    "DEVELOPMENT_BUILD" : "மேம்பாட்டு உருவாக்கம்",
    "RELOAD_FROM_DISK" : "வட்டில் இருந்து மீண்டும் ஏற்று",
    "KEEP_CHANGES_IN_EDITOR" : "மாற்றங்களை எடிட்டரில் வைத்திரு",
    "CLOSE_DONT_SAVE" : "மூடு (சேமிக்க வேண்டாம்)",
    "RELAUNCH_CHROME" : "Chrome ஐ மீண்டும் தொடங்கு",
    "ABOUT" : "பற்றி",
    "CLOSE" : "மூடு",
    "ABOUT_TEXT_LINE1" : "வெளியிடு {VERSION_MAJOR}.{VERSION_MINOR}, {BUILD_TYPE} {VERSION}",
    "ABOUT_TEXT_BUILD_TIMESTAMP" : "உருவாக்கு நேர முத்திரை: ",
    "ABOUT_TEXT_LINE3" : "மூன்றாம் தரப்பு மென்பொருள் அறிவிப்புகள் மற்றும் விதிமுறைகள் <a href='{ADOBE_THIRD_PARTY}'>{ADOBE_THIRD_PARTY}</a> இல் அமைந்துள்ளன, மேலும் இங்கே குறிப்பு மூலம் இணைக்கப்பட்டுள்ளன.",
    "ABOUT_TEXT_LINE4" : "ஆவணப்படுத்தல் மற்றும் மூலக் குறியீடு <a href='https://github.com/brackets-cont/brackets/'>https://github.com/brackets-cont/brackets/</a> இல் உள்ளது",
    "ABOUT_TEXT_LINE5" : "அவர்கள் இதை \u2764 மற்றும் JavaScript உடன் செய்தார்கள்:",
    "ABOUT_TEXT_LINE6" : "பலர் (ஆனால் இப்போது இந்தத் தரவை ஏற்றுவதில் எங்களுக்கு சிக்கல் உள்ளது)",
    "ABOUT_TEXT_MDN_DOCS" : "MDN ஆவணங்கள் மற்றும் MDN கிராஃபிக் லோகோ ஆகியவை கிரியேட்டிவ் காமன்ஸ் பண்புக்கூறு \u2011 உரிமத்தின் கீழ் உரிமம் பெற்றவை, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
    "UPDATE_NOTIFICATION_TOOLTIP" : "{APP_NAME} இன் புதிய பதிப்பு கிடைக்கிறது! மேலும் தகவலுக்கு இங்கே கிளிக் செய்யவும்.",
    "UPDATE_AVAILABLE_TITLE" : "புதுப்பிப்பு கிடைக்கிறது",
    "UPDATE_MESSAGE" : "வணக்கம், {APP_NAME} இன் புதிய பதிப்பு கிடைக்கிறது. புதிய அம்சங்கள் சில இங்கே:",
    "GET_IT_NOW" : "இப்போதே பெறுங்கள்!",
    "PROJECT_SETTINGS_TITLE" : "{0} க்கான திட்ட அமைப்புகள்",
    "PROJECT_SETTING_BASE_URL" : "அடிப்படை URL ஐ முன்னோட்டமிடுங்கள்",
    "PROJECT_SETTING_BASE_URL_HINT" : "ஒரு URL ஐ உள்ளிட்டு உள்ளூர் சேவையகத்தைப் பயன்படுத்தவும் http://localhost:8000/",
    "BASEURL_ERROR_INVALID_PROTOCOL" : "முன்னோட்டம் {0} நெறிமுறையை ஆதரிக்கவில்லை. http: அல்லது https: \u2011format ஐப் பயன்படுத்தவும்.",
    "BASEURL_ERROR_SEARCH_DISALLOWED" : "URL இல் “{0}” போன்ற தேடல் அளவுருக்கள் இருக்கக்கூடாது.",
    "BASEURL_ERROR_HASH_DISALLOWED" : "URL இல் “{0}” போன்ற ஹாஷ் எழுத்துக்கள் இருக்கக்கூடாது.",
    "BASEURL_ERROR_INVALID_CHAR" : "“{0}” போன்ற சிறப்பு எழுத்துக்கள் %-குறியாக்கப்பட்டிருக்க வேண்டும்.",
    "BASEURL_ERROR_UNKNOWN_ERROR" : "URL ஐ பாகுபடுத்துவதில் தெரியாத பிழை",
    
    // Pane.js க்கான சரங்கள்
    "EMPTY_VIEW_HEADER" : "<em>இந்த பலகத்துடன் கோப்பைத் திறக்கவும் தேர்ந்தெடுக்கப்பட்டது</em>",
    "FLIPVIEW_BTN_TOOLTIP" : "இந்தக் காட்சியை {0} பலகத்தில் புரட்டு",
    
    // themes-settings.html மற்றும் themes-general.html க்கான சரங்கள்
    "CURRENT_THEME" : "தற்போதைய தீம்",
    "USE_THEME_SCROLLBARS" : "தீம் உருள் பட்டிகளைப் பயன்படுத்தவும்",
    "FONT_SIZE" : "எழுத்துரு அளவு",
    "FONT_FAMILY" : "எழுத்துரு குடும்பம்",
    "THEMES_SETTINGS" : "தீம் அமைப்புகள்",
    
    // CSS விரைவுத் திருத்தம்
    "BUTTON_NEW_RULE" : "புதிய விதி",
    
    // நீட்டிப்பு மேலாண்மை சரங்கள்
    "நிறுவு" : "நிறுவு",
    "புதுப்பி" : "புதுப்பி",
    "நீக்கு" : "நீக்கு",
    "முடக்கு" : "முடக்கு",
    "செயல்படுத்து" : "செயல்படுத்து",
    "மேலெழுது" : "மேலெழுது",
    "CANT_REMOVE_DEV" : "”dev” கோப்புறையில் உள்ள நீட்டிப்புகளை நீங்கள் கைமுறையாக அகற்ற வேண்டும்.",
    "CANT_UPDATE" : "நீட்டிப்பு {APP_NAME} இன் இந்தப் பதிப்போடு இணக்கமாக இல்லை.",
    "CANT_UPDATE_DEV" : "”dev” கோப்புறையில் உள்ள நீட்டிப்புகளை தானாகப் புதுப்பிக்க முடியாது.",
    "INSTALL_EXTENSION_TITLE" : "நீட்டிப்பை நிறுவு",
    "UPDATE_EXTENSION_TITLE" : "நீட்டிப்பைப் புதுப்பிக்கவும்",
    "INSTALL_EXTENSION_LABEL" : "நீட்டிப்பு URL",
    "INSTALL_EXTENSION_HINT" : "நீட்டிப்பு ஜிப் கோப்பு URL அல்லது GitHub களஞ்சியம்",
    "INSTALLING_FROM" : "{0}\u2026 இலிருந்து நீட்டிப்பை நிறுவுகிறது",
    "INSTALL_SUCCEEDED" : "நிறுவல் முடிந்தது!",
    "INSTALL_FAILED" : "நிறுவல் தோல்வியடைந்தது.",
    "CANCELING_INSTALL" : "ரத்துசெய்கிறது\u2026",
    "CANCELING_HUNG" : "நிறுவலை ரத்து செய்வது நீண்ட நேரம் எடுக்கிறது. ஒரு உள் பிழை ஏற்பட்டிருக்கலாம்.",
    "INSTALL_CANCELED" : "நிறுவல் ரத்து செய்யப்பட்டது.",
    "VIEW_COMPLETE_DESCRIPTION" : "முழு விளக்கத்தைக் காண்க",
    "VIEW_TRUNCATED_DESCRIPTION" : "துண்டிக்கப்பட்ட விளக்கத்தைக் காண்க",
    "SORT_EXTENSION_METHOD" : "பதிவிறக்க எண்ணிக்கை அல்லது புதுப்பிப்பு நேரத்தின்படி நீட்டிப்புகளை வரிசைப்படுத்து",
    // இவை நீட்டிப்புகள் டொமைனில் உள்ள பிழைக் குறியீடுகளுடன் பொருந்த வேண்டும்.* :
    "INVALID_ZIP_FILE" : "பதிவிறக்கப்பட்ட உள்ளடக்கம் செல்லுபடியாகும் ஜிப் கோப்பு அல்ல.",
    "MISSING_PACKAGE_JSON" : "தொகுப்பில் package.json கோப்பு இல்லை.",
    "INVALID_PACKAGE_JSON" : "package.json கோப்பு தவறானது. (பிழை {0}.)",
    "MISSING_PACKAGE_NAME" : "package.json கோப்பில் தொகுப்பு பெயர் இல்லை.",
    "BAD_PACKAGE_NAME" : "{0} என்பது தவறான தொகுப்பு. name.",
    "MISSING_PACKAGE_VERSION" : "package.json கோப்பில் தொகுப்பு பதிப்பு இல்லை.",
    "INVALID_VERSION_NUMBER" : "தொகுப்பு பதிப்பு எண் ({0}) தவறானது.",
    "INVALID_BRACKETS_VERSION" : "{APP_NAME} இணக்கத்தன்மை சரம் ({0}) தவறானது.",
    "DISALLOWED_WORDS" : "{0} புலத்தில் ({1}) என்ற சொற்கள் அனுமதிக்கப்படவில்லை.",
    "NPM_INSTALL_FAILED" : "npm நிறுவல் தோல்வியடைந்தது: {0}",
    "API_NOT_COMPATIBLE" : "நீட்டிப்பு {APP_NAME} இன் இந்தப் பதிப்போடு இணக்கமாக இல்லை. இது காலாவதியான நீட்டிப்புகள் கோப்புறையில் நிறுவப்பட்டது.",
    "MISSING_MAIN" : "தொகுப்பில் main.js கோப்பு இல்லை.",
    "EXTENSION_ALREADY_INSTALLED" : "இந்த தொகுப்பை நிறுவுவது முன்பு நிறுவப்பட்ட நீட்டிப்பை மாற்றும். பழைய நீட்டிப்பை மாற்ற விரும்புகிறீர்களா?",
    "EXTENSION_SAME_VERSION" : "இந்த தொகுப்பின் பதிப்பு ஏற்கனவே நிறுவப்பட்டதைப் போன்றது. தற்போதைய நிறுவலை மாற்ற விரும்புகிறீர்களா?",
    "EXTENSION_OLDER_VERSION" : "இந்த தொகுப்பில் {0} பதிப்பு உள்ளது, இது ஏற்கனவே நிறுவப்பட்டதை விட பழையது ({1}). தற்போதைய நிறுவலை மாற்ற விரும்புகிறீர்களா?",
    "DOWNLOAD_ID_IN_USE" : "உள் பிழை: பதிவிறக்க ஐடி ஏற்கனவே பயன்பாட்டில் உள்ளது.",
    "NO_SERVER_RESPONSE" : "சேவையகத்துடன் இணைக்க முடியவில்லை.",
    "BAD_HTTP_STATUS" : "சேவையகத்தில் கோப்பு காணப்படவில்லை (HTTP {0}).",
    "CANNOT_WRITE_TEMP" : "தற்காலிக கோப்பில் பதிவிறக்கத்தைச் சேமிக்க முடியவில்லை.",
    "ERROR_LOADING" : "நீட்டிப்பைத் தொடங்கும்போது பிழை ஏற்பட்டது.",
    "MALFORMED_URL" : "URL தவறான வடிவத்தில் உள்ளது. நீங்கள் சரியாக தட்டச்சு செய்துள்ளீர்களா என்பதை சரிபார்க்கவும்.",
    "UNSUPPORTED_PROTOCOL" : "URL http அல்லது https வடிவத்தில் இருக்க வேண்டும்.",
    "UNKNOWN_ERROR" : "தெரியாத உள் பிழை.",
    // NOT_FOUND_ERR க்கு, மேலே உள்ள பொதுவான சரங்களைக் காண்க
    "EXTENSION_MANAGER_TITLE" : "நீட்டிப்பு மேலாளர்",
    "EXTENSION_MANAGER_ERROR_LOAD" : "நீட்டிப்பு பதிவேட்டை அணுகுவதில் பிழை. பின்னர் மீண்டும் முயற்சிக்கவும்.",
    "INSTALL_EXTENSION_DRAG" : ".zip தொகுப்பை இங்கே இழுக்கவும் அல்லது",
    "INSTALL_EXTENSION_DROP" : "நிறுவ .zip தொகுப்பை விடுங்கள்",
    "INSTALL_EXTENSION_DROP_ERROR" : "பின்வரும் பிழைகள் காரணமாக நிறுவல் அல்லது புதுப்பிப்பு தோல்வியடைந்தது:",
    "INSTALL_FROM_URL" : "URL இலிருந்து நிறுவு\u2026",
    "INSTALL_EXTENSION_VALIDATING" : "சரிபார்க்கிறது\u2026",
    "EXTENSION_AUTHOR" : "ஆசிரியர்",
    "EXTENSION_DATE" : "தேதி",
    "EXTENSION_INCOMPATIBLE_NEWER" : "இந்த நீட்டிப்புக்கு {APP_NAME} இன் புதிய பதிப்பு தேவை.",
    "EXTENSION_INCOMPATIBLE_OLDER" : "இந்த நீட்டிப்பு தற்போது பழைய பதிப்புகளுடன் மட்டுமே இயங்குகிறது {APP_NAME}.",
    "EXTENSION_LATEST_INCOMPATIBLE_NEWER" : "இந்த நீட்டிப்பு பதிப்பு {0} க்கு {APP_NAME} இன் புதிய பதிப்பு தேவை, ஆனால் நீங்கள் முந்தைய பதிப்பு {1} ஐ நிறுவலாம்.",
    "EXTENSION_LATEST_INCOMPATIBLE_OLDER" : "இந்த நீட்டிப்பு பதிப்பு {0} {APP_NAME} இன் பழைய பதிப்புகளுடன் மட்டுமே செயல்படும், ஆனால் நீங்கள் முந்தைய பதிப்பு {1} ஐ நிறுவலாம்.",
    "EXTENSION_NO_DESCRIPTION" : "விளக்கம் இல்லை",
    "EXTENSION_MORE_INFO" : "மேலும் தகவல்\u2026",
    "EXTENSION_ERROR" : "நீட்டிப்பு பிழை",
    "EXTENSION_KEYWORDS" : "முக்கிய வார்த்தைகள்",
    "EXTENSION_TRANSLATED_USER_LANG" : "உங்களுடையது உட்பட {0} மொழிகளில் மொழிபெயர்க்கப்பட்டுள்ளது",
    "EXTENSION_TRANSLATED_GENERAL" : "மொழிகள் {0} இல் மொழிபெயர்க்கப்பட்டுள்ளது",
    "EXTENSION_TRANSLATED_LANGS" : "இந்த நீட்டிப்பு இந்த மொழிகளில் மொழிபெயர்க்கப்பட்டுள்ளது: {0}",
    "EXTENSION_INSTALLED" : "நிறுவப்பட்டது",
    "EXTENSION_UPDATE_INSTALLED" : "இந்த நீட்டிப்பு புதுப்பிப்பு பதிவிறக்கம் செய்யப்பட்டுள்ளது, மேலும் {APP_NAME} மீண்டும் ஏற்றப்பட்ட பிறகு நிறுவப்படும்.",
    "EXTENSION_SEARCH_PLACEHOLDER" : "தேடல்",
    "EXTENSION_MORE_INFO_LINK" : "மேலும்",
    "BROWSE_EXTENSIONS" : "நீட்டிப்புகளை உலாவுக",
    "EXTENSION_MANAGER_REMOVE" : "நீட்டிப்பை அகற்று",
    "EXTENSION_MANAGER_REMOVE_ERROR" : "குறைந்தது ஒரு நீட்டிப்பையாவது அகற்ற முடியவில்லை: {0}. {APP_NAME} இன்னும் மீண்டும் ஏற்றப்படும்.",
    "EXTENSION_MANAGER_UPDATE" : "நீட்டிப்பைப் புதுப்பிக்கவும்",
    "EXTENSION_MANAGER_UPDATE_ERROR" : "குறைந்தது ஒரு நீட்டிப்பையாவது புதுப்பிக்க முடியவில்லை: {0}. {APP_NAME} இன்னும் மீண்டும் ஏற்றப்படும்.",
    "EXTENSION_MANAGER_DISABLE" : "நீட்டிப்பை முடக்கு",
    "EXTENSION_MANAGER_DISABLE_ERROR" : "குறைந்தது ஒரு நீட்டிப்பையாவது முடக்க முடியவில்லை: {0}. {APP_NAME} இன்னும் மீண்டும் ஏற்றப்படும்.",
    "MARKED_FOR_REMOVAL" : "அகற்றுவதற்கு குறிக்கப்பட்டது",
    "UNDO_REMOVE" : "செயல்தவிர்",
    "MARKED_FOR_UPDATE" : "புதுப்பிப்புக்காக குறிக்கப்பட்டது",
    "UNDO_UPDATE" : "செயல்தவிர்",
    "MARKED_FOR_DISABLING" : "முடக்கப்பட வேண்டியதாக குறிக்கப்பட்டது",
    "UNDO_DISABLE" : "செயல்தவிர்",
    "CHANGE_AND_RELOAD_TITLE" : "நீட்டிப்புகளை மாற்று",
    "CHANGE_AND_RELOAD_MESSAGE" : "தேர்ந்தெடுக்கப்பட்ட நீட்டிப்புகளைப் புதுப்பிக்க, அகற்ற அல்லது முடக்க, {APP_NAME} ஐ மீண்டும் ஏற்ற வேண்டும். சேமிக்கப்படாத மாற்றங்களைச் சேமிக்க உங்களுக்கு நினைவூட்டப்படும்.",
    "REMOVE_AND_RELOAD" : "நீட்டிப்புகளை அகற்றி மீண்டும் ஏற்றவும்",
    "CHANGE_AND_RELOAD" : "நீட்டிப்புகளை மாற்றவும் மீண்டும் ஏற்றவும்",
    "UPDATE_AND_RELOAD" : "நீட்டிப்புகளைப் புதுப்பித்து மீண்டும் ஏற்றவும்",
    "DISABLE_AND_RELOAD" : "நீட்டிப்புகளை முடக்கி மீண்டும் ஏற்றவும்",
    "PROCESSING_EXTENSIONS" : "நீட்டிப்பு மாற்றங்களைச் செயலாக்குதல்\u2026",
    "EXTENSION_NOT_INSTALLED" : "நீட்டிப்பு {0} நிறுவப்படாததால் அதை அகற்ற முடியாது.",
    "NO_EXTENSIONS" : "நீட்டிப்புகள் எதுவும் இன்னும் நிறுவப்படவில்லை.<br>தொடங்குவதற்கு மேலே உள்ள கிடைக்கும் தாவலைக் கிளிக் செய்யவும்.",
    "NO_EXTENSION_MATCHES" : "உங்கள் தேடலுடன் பொருந்தக்கூடிய நீட்டிப்புகள் எதுவும் இல்லை.",
    "REGISTRY_SANITY_CHECK_WARNING" : "குறிப்பு: இந்த நீட்டிப்புகள் {APP_NAME} ஐத் தவிர வேறு மூலங்களிலிருந்து வரக்கூடும். நீட்டிப்புகள் சரிபார்க்கப்படவில்லை மற்றும் முழு உள்ளூர் அனுமதிகளையும் கொண்டுள்ளன. அறியப்படாத மூலங்களிலிருந்து நீட்டிப்புகளை நிறுவும் போது கவனமாக இருங்கள்.",
    "EXTENSIONS_INSTALLED_TITLE" : "நிறுவப்பட்டது",
    "EXTENSIONS_AVAILABLE_TITLE" : "கிடைக்கிறது",
    "EXTENSIONS_THEMES_TITLE" : "தீம்கள்",
    "EXTENSIONS_UPDATES_TITLE" : "புதுப்பிப்புகள்",
    "EXTENSIONS_LAST_UPDATED" : "புதுப்பிக்கப்பட்டது",
    "EXTENSIONS_DOWNLOADS" : "பதிவிறக்கங்கள்",
    
    "INLINE_EDITOR_NO_MATCHES" : "பொருத்தங்கள் எதுவும் கிடைக்கவில்லை.",
    "INLINE_EDITOR_HIDDEN_MATCHES" : "அனைத்து பொருத்தங்களும் சுருக்கப்பட்டுள்ளன. பொருத்தங்களைக் காண வலதுபுறத்தில் பட்டியலிடப்பட்டுள்ள கோப்புகளை விரிவாக்குங்கள்.",
    "CSS_QUICK_EDIT_NO_MATCHES" : "உங்கள் தேர்வுடன் பொருந்தக்கூடிய CSS விதிகள் எதுவும் இல்லை.<br> ”புதிய விதி” என்பதைக் கிளிக் செய்வதன் மூலம் ஒன்றை உருவாக்கவும்.",
    "CSS_QUICK_EDIT_NO_STYLESHEETS" : "திட்டத்தில் எந்த ஸ்டைல்ஷீட்களும் இல்லை.<br> CSS விதிகளைச் சேர்க்க ஒன்றை உருவாக்கவும்.",
    
    // தனிப்பயன் பார்வையாளர்கள்
    "IMAGE_VIEWER_LARGEST_ICON" : "மிகப்பெரியது",
    
    /**
    * அலகு பெயர்கள்
    */
    "UNIT_PIXELS" : "பிக்சல்கள்",
    
    // நீட்டிப்புகள்/இயல்புநிலை/DebugCommands
    "DEBUG_MENU" : "மேம்பாடு",
    "ERRORS" : "பிழைகள்",
    "CMD_SHOW_DEV_TOOLS" : "மேம்பாட்டு கருவிகளைக் காட்டு",
    "CMD_REFRESH_WINDOW" : "நீட்டிப்புகள் மூலம் மீண்டும் ஏற்று",
    "CMD_RELOAD_WITHOUT_USER_EXTS" : "நீட்டிப்புகள் இல்லாமல் மீண்டும் ஏற்று",
    "CMD_NEW_BRACKETS_WINDOW" : "புதிய {APP_NAME} சாளரம்",
    "CMD_LAUNCH_SCRIPT_MAC" : "கட்டளை வரி குறுக்குவழியை நிறுவு",
    "CMD_SWITCH_LANGUAGE" : "மொழியை மாற்று",
    "CMD_RUN_UNIT_TESTS" : "சோதனைகளை இயக்கு",
    "CMD_SHOW_PERF_DATA" : "செயல்திறன் தரவைக் காட்டு",
    "CMD_ENABLE_NODE_DEBUGGER" : "முனை பிழைத்திருத்தியை இயக்கு",
    "CMD_LOG_NODE_STATE" : "முனை நிலையை பதிவு செய் console",
    "CMD_RESTART_NODE" : "முனையை மீண்டும் தொடங்கு",
    "CMD_SHOW_ERRORS_IN_STATUS_BAR" : "நிலைப் பட்டியில் பிழைகளைக் காட்டு",
    "CMD_OPEN_BRACKETS_SOURCE" : "{APP_NAME} மூலத்தைத் திற",
    
    "CREATING_LAUNCH_SCRIPT_TITLE" : "{APP_NAME} க்கான கட்டளை வரி குறுக்குவழி",
    "ERROR_CREATING_LAUNCH_SCRIPT" : "கட்டளை வரி குறுக்குவழியை நிறுவும் போது பிழை ஏற்பட்டது. <a href='https://github.com/brackets-cont/brackets/wiki/Command-Line-Arguments#troubleshooting'>இந்த சரிசெய்தல் படிகளை</a> முயற்சிக்கவும்.<br/><br/>காரணம்: {0}",
    "ERROR_CLTOOLS_RMFAILED" : "ஏற்கனவே உள்ள குறியீட்டு இணைப்பை அகற்ற முடியவில்லை <code>/usr/local/bin/backets</code>.",
    "ERROR_CLTOOLS_MKDIRFAILED" : "கோப்பகத்தை உருவாக்க முடியவில்லை <code>/usr/local/bin</code>.",
    "ERROR_CLTOOLS_LNFAILED" : "குறியீட்டு இணைப்பை உருவாக்க முடியவில்லை <code>/usr/local/bin/brackets</code>.",
    "ERROR_CLTOOLS_SERVFAILED" : "உள் பிழை.",
    "ERROR_CLTOOLS_NOTSUPPORTED" : "இந்த இயக்க முறைமையில் கட்டளை வரி குறுக்குவழி ஆதரிக்கப்படவில்லை.",
    "LAUNCH_SCRIPT_CREATE_SUCCESS" : "வெற்றி! இப்போது நீங்கள் கட்டளை வரியிலிருந்து {APP_NAME} ஐ எளிதாகத் திறக்கலாம்: <code>brackets file.txt</code> கட்டளையுடன் கோப்பைத் திறக்கவும் அல்லது <code>brackets கோப்புறை</code> கட்டளையுடன் திட்டத்தை மாற்றவும். <br/><br/><a href='https://github.com/brackets-cont/brackets/wiki/Command-Line-Arguments'>கட்டளை வரியிலிருந்து {APP_NAME} ஐப் பயன்படுத்துவது பற்றி மேலும் படிக்கவும்.</a>",
    
    "LANGUAGE_TITLE" : "மொழியை மாற்று",
    "LANGUAGE_MESSAGE" : "மொழி:",
    "LANGUAGE_SUBMIT" : "{APP_NAME} ஐப் புதுப்பிக்கவும்",
    "LANGUAGE_CANCEL" : "ரத்துசெய்",
    "LANGUAGE_SYSTEM_DEFAULT" : "கணினி இயல்புநிலை",
    
    // நீட்டிப்புகள்/இயல்புநிலை/HealthData
    "HEALTH_DATA_NOTIFICATION" : "சுகாதார அறிக்கை அமைப்புகள்",
    "HEALTH_FIRST_POPUP_TITLE" : "{APP_NAME} சுகாதார அறிக்கை",
    "HEALTH_DATA_DO_TRACK" : "எனது {APP_NAME} பயன்பாடு பற்றிய அநாமதேய தரவைப் பகிரவும்",
    "HEALTH_DATA_NOTIFICATION_MESSAGE" : "உங்களுக்கு உதவ {APP_NAME} ஐ மேம்படுத்த, நீங்கள் தயாரிப்பை எவ்வாறு பயன்படுத்துகிறீர்கள் என்பது பற்றிய brackets.io வரையறுக்கப்பட்ட, <strong>அநாமதேய</strong> புள்ளிவிவரங்களை நாங்கள் தொடர்ந்து அனுப்புகிறோம். இந்தத் தகவல் அம்சங்களை முன்னுரிமைப்படுத்தவும், பிழைகளைக் கண்டறியவும், பயன்பாட்டு சிக்கல்களைக் கண்டறியவும் உதவுகிறது.<br><br>உதவி > சுகாதார அறிக்கை</strong> என்பதைத் தேர்ந்தெடுப்பதன் மூலம் உங்கள் தரவைப் பார்க்கலாம் அல்லது பகிர்வதைத் தவிர்க்கலாம்.<br><br><a href='https://github.com/brackets-cont/brackets/wiki/Health-Data'>{APP_NAME} இன் சுகாதார அறிக்கை</a> பற்றி மேலும் படி",
    "HEALTH_DATA_PREVIEW" : "{APP_NAME} இன் சுகாதார அறிக்கை",
    "HEALTH_DATA_PREVIEW_INTRO" : "<p>{APP_NAME} ஐ மேம்படுத்த எங்களுக்கு உதவ, நீங்கள் தயாரிப்பை எவ்வாறு பயன்படுத்துகிறீர்கள் என்பது பற்றிய brackets.io வரையறுக்கப்பட்ட, <strong>அநாமதேய</strong> புள்ளிவிவரங்களை நாங்கள் தொடர்ந்து அனுப்புகிறோம். இந்தத் தகவல் அம்சங்களை முன்னுரிமைப்படுத்தவும், பிழைகளைக் கண்டறியவும், பயன்பாட்டு சிக்கல்களைக் கண்டறியவும் எங்களுக்கு உதவுகிறது. <a> href='https://github.com/brackets-cont/brackets/wiki/Health-Data'>{APP_NAME} இன் சுகாதார அறிக்கை</a> மற்றும் உங்கள் தனியுரிமையைப் பாதுகாக்கும் அதே வேளையில் அது {APP_NAME} சமூகத்திற்கு எவ்வாறு பயனளிக்கிறது என்பதைப் பற்றி மேலும் படிக்கவும்.</p><p>இயக்கப்பட்டிருந்தால் உங்கள் அடுத்த சுகாதார அறிக்கையில் அனுப்பப்படும் தகவலின் முன்னோட்டம் கீழே உள்ளது.</p>",
    
    // extensions/default/InlineTimingFunctionEditor
    "INLINE_TIMING_EDITOR_TIME" : "நேரம்",
    "INLINE_TIMING_EDITOR_PROGRESSION" : "முன்னேற்றம்",
    "BEZIER_EDITOR_INFO" : "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> தேர்ந்தெடுக்கப்பட்ட புள்ளியை நகர்த்தவும்<br><kbd class='text'>Shift</kbd> பத்து நகர்த்தவும் அலகுகள்<br><kbd class='text'>தாவல்</kbd>புள்ளிகளை மாற்றுதல்",
    "STEPS_EDITOR_INFO" : "<kbd>↑</kbd><kbd>↓</kbd>படிகளை அதிகரிக்கவும் குறைக்கவும்<br><kbd>←</kbd><kbd>→</kbd> ”தொடங்கு” அல்லது ”முடிவு”",
    "INLINE_TIMING_EDITOR_INVALID" : "பழைய மதிப்பு <code>{0}</code> தவறானது, எனவே காட்டப்படும் செயல்பாடு <code>{1}</code> ஆக மாற்றப்பட்டது. முதல் திருத்தத்துடன் ஆவணம் புதுப்பிக்கப்படும்.",
    
    // நீட்டிப்புகள்/இயல்புநிலை/InlineColorEditor
    "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP" : "தற்போதைய நிறம்",
    "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP" : "அசல் நிறம்",
    "COLOR_EDITOR_RGBA_BUTTON_TIP" : "RGBa வடிவம்",
    "COLOR_EDITOR_HEX_BUTTON_TIP" : "ஹெக்ஸ் வடிவம்",
    "COLOR_EDITOR_HSLA_BUTTON_TIP" : "HSLA வடிவம்",
    "COLOR_EDITOR_0X_BUTTON_TIP" : "ஹெக்ஸ் (0x) \u2011வடிவமைப்பு",
    "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR" : "{0} ({1} முறை பயன்படுத்தப்பட்டது)",
    "COLOR_EDITOR_USED_COLOR_TIP_PLURAL" : "{0} ({1} முறை பயன்படுத்தப்பட்டது)",
    
    // நீட்டிப்புகள்/இயல்புநிலை/JavaScriptCodeHints
    "CMD_JUMPTO_DEFINITION" : "வரையறைக்குச் செல்லவும்",
    "CMD_SHOW_PARAMETER_HINT" : "அளவுருவைக் காட்டு குறிப்பு",
    "NO_ARGUMENTS" : "<parametaries இல்லை",
    "DETECTED_EXCLUSION_TITLE" : "JavaScript கோப்பு அனுமான சிக்கல்",
    "DETECTED_EXCLUSION_INFO" : "{APP_NAME} <span class='dialog-filename'>{0}</span> கோப்பை செயலாக்குவதில் சிக்கலை எதிர்கொண்டது.<br><br>குறியீட்டு குறிப்புகள், வரையறைக்கு தாவுதல் அல்லது விரைவான திருத்தம் ஆகியவற்றிற்காக இந்த கோப்பு இனி செயலாக்கப்படவில்லை. திட்டத்தின் <code>.brackets.json</code> கோப்பைத் திறந்து, கோப்பைத் திரும்பப் பெற <code>jscodehints.detectedExclusions</code> ஐத் திருத்தவும்.<br><br>இது {APP_NAME} இல் ஒரு பிழையாக இருக்கலாம். இந்தக் கோப்பின் நகலை நீங்கள் வழங்க முடிந்தால், தயவுசெய்து <a href='https://github.com/brackets-cont/brackets/wiki/How-to-Report-an-Issue'>பிழையைப் புகாரளி</a> மற்றும் கோப்பிற்கான இணைப்பைச் சேர்க்கவும்!",
    
    // extensions/default/JSLint
    "JSLINT_NAME" : "JSLint",
    
    // நீட்டிப்புகள்/இயல்புநிலை/விரைவுக்காட்சி
    "CMD_ENABLE_QUICK_VIEW" : "ஹோவரில் விரைவுக் காட்சி",
    
    // நீட்டிப்புகள்/இயல்புநிலை/சமீபத்திய திட்டங்கள்
    "CMD_TOGGLE_RECENT_PROJECTS" : "சமீபத்திய திட்டங்கள்",
    
    // நீட்டிப்புகள்/இயல்புநிலை/MDNDocs
    "DOCS_MORE_LINK" : "மேலும் படிக்க",
    
    // நீட்டிப்புகள்/இயல்புநிலை/குறியீட்டு மடிப்பு
    "COLLAPSE_ALL" : "அனைத்தையும் சுருக்கு",
    "EXPAND_ALL" : "அனைத்தையும் விரிவாக்கு",
    "COLLAPSE_CURRENT" : "தற்போதையத்தைச் சுருக்கு",
    "EXPAND_CURRENT" : "தற்போதையத்தைச் சுருக்கு",
    
    // நீட்டிப்புகள்/இயல்புநிலை/வழிசெலுத்தல் மற்றும் வரலாறு
    "RECENT_FILES_DLG_HEADER" : "சமீபத்திய கோப்புகள்",
    "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL" : "அழி",
    "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE" : "பணிப்பட்டியலில் இல்லாத கோப்புகளை அழி",
    
    // முக்கிய விருப்பங்களின் விளக்கங்கள்
    "DESCRIPTION_CLOSE_BRACKETS" : "சரி: சுருள் அடைப்புக்குறிகள், அடைப்புக்குறிகள் மற்றும் அடைப்புக்குறிகளை தானாக மூடு",
    "DESCRIPTION_CLOSE_OTHERS_ABOVE" : "தவறு: பணி கோப்புகளின் சூழல் மெனுவிலிருந்து மேலே உள்ள மற்றவற்றை மூடு விருப்பத்தை அகற்று",
    "DESCRIPTION_CLOSE_OTHERS_BELOW" : "தவறு: பணி கோப்புகளின் சூழல் மெனுவிலிருந்து கீழே உள்ள மற்றவற்றை மூடு விருப்பத்தை அகற்று",
    "DESCRIPTION_CLOSE_OTHERS" : "தவறு: பணி கோப்புகளின் சூழல் மெனுவிலிருந்து மற்றவற்றை மூடு",
    "DESCRIPTION_CLOSE_OTHERS" : "தவறு: பணி கோப்புகளின் சூழல் மெனுவிலிருந்து மற்றவற்றை மூடு",
    "DESCRIPTION_CLOSE_TAGS" : "குறிச்சொல் மூடும் விருப்பங்களை அமைக்கிறது",
    "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS" : "தானாக மூடப்படக்கூடாத குறிச்சொற்களின் அட்டவணை",
    "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING" : "குறிச்சொல்லைத் திறக்கும்போது மூடு > எழுதப்படும்",
    "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING" : "குறிச்சொல்லை மூடும்போது மூடு / தட்டச்சு செய்யப்படும்",
    "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS" : "திறக்கும்போது வெற்று வரியைக் கொண்டிருக்கும் குறிச்சொற்களின் அட்டவணை",
    "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD" : "உண்மை: உள்தள்ளல் நிலை மாறும்போது எப்போதும் உள்தள்ளல் குறிகளை உருவாக்கு",
    "DESCRIPTION_CODE_FOLDING_ENABLED" : "உண்மை: குறியீட்டை மடிப்பதை இயக்கு",
    "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER" : "உண்மை: கர்சர் இடது ஓரத்திற்கு நகர்த்தப்படும்போது உள்தள்ளல் குறிகளை மட்டும் காட்டு",
    "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL" : "Collapse All விருப்பம் எத்தனை நிலைகளை ஆழமாக பாதிக்கிறது என்பதைக் கட்டுப்படுத்துகிறது",
    "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE" : "சுருக்கப் பிரிவு ஐகான் தோன்றுவதற்கு முன் குறைந்தபட்சம் வரிசைகளாவது",
    "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES" : "சரி: கோப்பு அல்லது திட்டம் மூடப்பட்டு மீண்டும் திறக்கப்பட்டால் சுருக்கப்பட்ட பிரிவுகளை நினைவில் கொள்ளுங்கள்",
    "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE" : "சரி: எடிட்டரில் தேர்ந்தெடுக்கப்பட்ட உரையின் குறியீட்டு மடிப்பை இயக்கு",
    "DESCRIPTION_ATTR_HINTS" : "HTML பண்புக்கூறு குறிப்புகளைக் காட்டு அல்லது மறை",
    "DESCRIPTION_CSS_PROP_HINTS" : "CSS/LESS/SCSS சொத்து குறிப்புகளைக் காட்டு அல்லது மறை",
    "DESCRIPTION_JS_HINTS" : "ஜாவாஸ்கிரிப்ட் குறியீடு குறிப்புகளைக் காட்டு அல்லது மறை",
    "DESCRIPTION_JS_HINTS_TYPE_DETAILS" : "தரவு வகை விவரங்களைக் காட்டு அல்லது மறை ஜாவாஸ்கிரிப்ட் குறியீடு குறிப்புகள்",
    "DESCRIPTION_PREF_HINTS" : "விருப்பத்தேர்வு குறியீடு குறிப்புகளைக் காட்டு அல்லது மறை",
    "DESCRIPTION_SPECIAL_CHAR_HINTS" : "HTML நிறுவனங்களுக்கான குறிப்புகளைக் காட்டு அல்லது மறை",
    "DESCRIPTION_SVG_HINTS" : "SVG குறியீட்டிற்கான குறிப்புகளைக் காட்டு அல்லது மறை",
    "DESCRIPTION_HTML_TAG_HINTS" : "HTML மற்றும் CSS/LESS/SCSS கோப்புகளில் URL குறிப்புகளைக் காட்டு அல்லது மறை",
    "DESCRIPTION_URL_CODE_HINTS" : "HTML மற்றும் CSS/LESS/SCSS கோப்புகளில் URL குறிப்புகளைக் காட்டு அல்லது மறை",
    "DESCRIPTION_DRAG_DROP_TEXT" : "இழுத்து விடுதலை இயக்கு அல்லது முடக்கு",
    "DESCRIPTION_HEALTH_DATA_TRACKING" : "சுகாதார கண்காணிப்பை இயக்கு",
    "DESCRIPTION_HIGHLIGHT_MATCHES" : "ஆவணம் முழுவதும் பொருந்தக்கூடிய சரங்களின் தானியங்கி சிறப்பம்சத்தை இயக்கு",
    "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN" : "தற்போதைய கர்சருடன் பொருந்தக்கூடிய அனைத்து சரங்களையும் சிறப்பித்துக் காட்டு (தேர்வு தேவையில்லை)",
    "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY" : "தேர்வு முழு சொற்றொடராக இருக்கும்போது மட்டும் சிறப்பித்துக் காட்டு",
    "DESCRIPTION_INSERT_HINT_ON_TAB" : "உண்மை: தாவலை அழுத்தும்போது தற்போது தேர்ந்தெடுக்கப்பட்ட குறியீடு குறிப்பைச் செருகவும் key",
    "DESCRIPTION_NO_HINTS_ON_DOT" : "true: . தட்டச்சு செய்யும்போது JS குறியீடு குறிப்புகளை தானாகக் காட்டாதே",
    "DESCRIPTION_JSLINT_OPTIONS" : "இயல்புநிலை JSLint அமைப்புகளைக் கொண்ட பொருள்",
    "DESCRIPTION_JSLINT_OPTIONS_ASS" : "true: நிலைசார் வெளிப்பாடுகளை அனுமதி",
    "DESCRIPTION_JSLINT_OPTIONS_BITWISE" : "true: பிட்வைஸ் ஆபரேட்டர்களை அனுமதி",
    "DESCRIPTION_JSLINT_OPTIONS_BROWSER" : "true: நிலையான உலாவி குளோபல்கள் முன் வரையறுக்கப்பட்டிருந்தால் உண்மை",
    "DESCRIPTION_JSLINT_OPTIONS_CLOSURE" : "true: Google Closure idioms ஐ அனுமதி",
    "DESCRIPTION_JSLINT_OPTIONS_COUNTUE" : "true: தொடர அனுமதி கட்டளை",
    "DESCRIPTION_JSLINT_OPTIONS_COUCH" : "true: CouchDB குளோபல்கள் இருக்க வேண்டும் என்றால் உண்மை",
    "DESCRIPTION_JSLINT_OPTIONS_DEBUG" : "உண்மை: பிழைத்திருத்தி கட்டளைகளை அனுமதி",
    "DESCRIPTION_JSLINT_OPTIONS_DEVEL" : "உண்மை, மேம்பாட்டிற்கு பயனுள்ள உலாவி குளோபல்கள் முன் வரையறுக்கப்பட்டவையாக இருந்தால்",
    "DESCRIPTION_JSLINT_OPTIONS_EQEQ" : "உண்மை: allow == and !=",
    "DESCRIPTION_JSLINT_OPTIONS_ES6" : "உண்மை, ES6 குளோபல்கள் முன் வரையறுக்கப்பட்டவையாக இருந்தால்",
    "DESCRIPTION_JSLINT_OPTIONS_EVIL" : "உண்மை: allow eval",
    "DESCRIPTION_JSLINT_OPTIONS_FORIN" : "உண்மை: வடிகட்டப்படாத ”for ... in”",
    "DESCRIPTION_JSLINT_OPTIONS_INDENT" : "குறிப்பிட்ட தாவல் எழுத்து அகலத்தை அமைக்கவும்",
    "DESCRIPTION_JSLINT_OPTIONS_MAXERR" : "அதிகபட்ச எச்சரிக்கைகளின் எண்ணிக்கை அறிக்கை",
    "DESCRIPTION_JSLINT_OPTIONS_MAXLEN" : "ஒரு வரிக்கு அதிகபட்ச எழுத்துகளின் எண்ணிக்கை",
    "DESCRIPTION_JSLINT_OPTIONS_NEWCAP" : "உண்மை: சிறிய எழுத்துக்களில் தொடங்கும் கட்டமைப்பாளர்களை அனுமதிக்கவும்",
    "DESCRIPTION_JSLINT_OPTIONS_NODE" : "உண்மை, Node.js குளோபல்கள் முன் வரையறுக்கப்பட்டிருக்க வேண்டும் என்றால்",
    "DESCRIPTION_JSLINT_OPTIONS_NOMEN" : "உண்மை: அடிக்கோடு தொடங்கும் அடையாளங்காட்டிகளை அனுமதிக்கவும்",
    "DESCRIPTION_JSLINT_OPTIONS_PASSFAIL" : "உண்மை: முதல் பிழையில் நிறுத்து",
    "DESCRIPTION_JSLINT_OPTIONS_PLUSPLUS" : "உண்மை: ++ மற்றும் --",
    "DESCRIPTION_JSLINT_OPTIONS_REGEXP" : "உண்மை: வழக்கமான வெளிப்பாடுகளில் . மற்றும் [^...].",
    "DESCRIPTION_JSLINT_OPTIONS_RHINO" : "சரி, ரைனோ குளோபல்கள் முன் வரையறுக்கப்பட்டதாக இருந்தால்",
    "DESCRIPTION_JSLINT_OPTIONS_SLOPPY" : "சரி: `use strict` directive ஐ விடுவி",
    "DESCRIPTION_JSLINT_OPTIONS_STUPID" : "சரி, (”...ஒத்திசைவு”) முறைகளைத் தடுக்க முடிந்தால்",
    "DESCRIPTION_JSLINT_OPTIONS_SUB" : "சரி: பயனற்ற அடைப்புக்குறி குறியீட்டை அனுமதிக்கவும்",
    "DESCRIPTION_JSLINT_OPTIONS_TODO" : "சரி: TODO கருத்துகளை அனுமதிக்கவும்",
    "DESCRIPTION_JSLINT_OPTIONS_UNPARAM" : "சரி: பயன்படுத்தப்படாத அளவுருக்களை அனுமதிக்கவும்",
    "DESCRIPTION_JSLINT_OPTIONS_VARS" : "சரி: ஒரு செயல்பாட்டில் பல var மாறிகளை அனுமதிக்கவும்",
    "DESCRIPTION_JSLINT_OPTIONS_WHITE" : "சரி: இடைவெளி விதிகளை புறக்கணிக்கவும்",
    "DESCRIPTION_LANGUAGE" : "மொழி சார்ந்தது விருப்பங்கள்",
    "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS" : "கோப்பு நீட்டிப்பிலிருந்து மொழி பெயருக்கு கூடுதல் இணைப்புகள்",
    "DESCRIPTION_LANGUAGE_FILE_NAMES" : "கோப்பு பெயரிலிருந்து மொழிக்கு பெயருக்கு கூடுதல் இணைப்புகள்",
    "DESCRIPTION_LINEWISE_COPY_CUT" : "தேர்வு இல்லாமல் நகலெடுத்து வெட்டுதல் நகலெடுக்கிறது அல்லது கர்சரைப் பயன்படுத்தி முழு வரிகளையும் வெட்டுகிறது",
    "DESCRIPTION_INPUT_STYLE" : "CodeMirror உள்ளீடு மற்றும் கவனத்தை எவ்வாறு கையாளுகிறது என்பதைத் தேர்வுசெய்கிறது. இது உரைப்பகுதியாக இருக்கலாம், இது இயல்புநிலையாக இருக்கலாம் அல்லது உள்ளடக்கத்தைத் திருத்தக்கூடியதாக இருக்கலாம், இது திரை வாசகர்களுக்கு சிறந்தது (ஆனால் நிலையற்றது)",
    "DESCRIPTION_LINETING_ENABLED" : "உண்மை: குறியீட்டைச் சரிபார்ப்பதை இயக்கு",
    "DESCRIPTION_ASYNC_TIMEOUT" : "நேரம் முடிந்த பிறகு ஒத்திசைவற்ற சரிபார்ப்பவர்கள் காலாவதியாகும் நேரம், மில்லி வினாடிகளில்",
    "DESCRIPTION_LINTING_PREFER" : "முதலில் இயக்க வேண்டிய சரிபார்ப்புகளின் அட்டவணை",
    "DESCRIPTION_LIVE_DEV_MULTIBROWSER" : "உண்மை: சோதனை முன்னோட்டத்தை இயக்கு",
    "DESCRIPTION_USE_PREFERED_ONLY" : "உண்மை: linting.prefer இல் குறிப்பிடப்பட்டுள்ள சரிபார்ப்புகளை மட்டும் இயக்கு",
    "DESCRIPTION_MAX_CODE_HINTS" : "ஒரே நேரத்தில் காண்பிக்க அதிகபட்ச குறியீடு குறிப்புகளின் எண்ணிக்கை",
    "DESCRIPTION_PATH" : "பாதை-குறிப்பிட்ட அமைப்புகள்",
    "DESCRIPTION_PROXY" : "செருகுநிரல்களை நிறுவுவதற்குப் பயன்படுத்தப்படும் ப்ராக்ஸி சேவையகத்திற்கான URL",
    "DESCRIPTION_SCROLL_PAST_END" : "உண்மை: ஆவணத்தின் முடிவைத் தாண்டி உருட்டுவதை இயக்கு",
    "DESCRIPTION_SHOW_CODE_HINTS" : "தவறு: அனைத்து குறியீடு குறிப்புகளையும் முடக்கு",
    "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING" : "உரை தேர்ந்தெடுக்கப்படும்போது கர்சர் தொடர்ந்து தெரியும்படி ஒளிரும்",
    "DESCRIPTION_SHOW_LINE_NUMBERS" : "உண்மை: இடது ஓரத்தில் வரி எண்களைக் காட்டு",
    "DESCRIPTION_SMART_INDENT" : "புதிய தொகுதியை உருவாக்கும்போது தானாகவே உள்தள்ளு",
    "DESCRIPTION_SOFT_TABS" : "தவறு: மென்மையான தாவல்களை முடக்கு",
    "DESCRIPTION_SORT_DIRECTORIES_FIRST" : "உண்மை: திட்ட மரத்தில் முதலில் கோப்பகங்களை வரிசைப்படுத்து",
    "DESCRIPTION_SPACE_UNITS" : "இடைவெளி அடிப்படையிலான உள்தள்ளலுக்குப் பயன்படுத்த வேண்டிய இடங்களின் எண்ணிக்கை",
    "DESCRIPTION_STATIC_SERVER_PORT" : "முன்னோட்டத்தில் உட்பொதிக்கப்பட்ட சேவையகம் பயன்படுத்த வேண்டிய போர்ட் எண்",
    "DESCRIPTION_STYLE_ACTIVE_LINE" : "உண்மை: கர்சர் பின்னணி நிறத்துடன் இருக்கும் வரியை முன்னிலைப்படுத்து",
    "DESCRIPTION_TAB_SIZE" : "தாவலில் காட்ட வேண்டிய இடங்களின் எண்ணிக்கை எழுத்துகள்",
    "DESCRIPTION_USE_TAB_CHAR" : "சரி: இடைவெளிகளுக்குப் பதிலாக தாவல்களைப் பயன்படுத்தவும்",
    "DESCRIPTION_UPPERCASE_COLORS" : "சரி: உள் வண்ண எடிட்டரில் பெரிய எழுத்து ஹெக்ஸ் வண்ணங்களை உருவாக்கவும்",
    "DESCRIPTION_WORD_WRAP" : "காட்சிப் பகுதியின் அகலத்தை மீறும் கோடுகளை உடைக்கவும்",
    "DESCRIPTION_DETECTED_EXCLUSIONS" : "டெர்ன் கட்டுப்பாட்டை மீறுவதாகக் கண்டறியப்பட்ட கோப்புகளின் பட்டியல்",
    "DESCRIPTION_INFERENCE_TIMEOUT" : "கோப்புகளைப் புரிந்துகொள்ள முயற்சிக்கும்போது டெர்ன் காலாவதியான நேரம்",
    "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR" : "சரி: நிலைப் பட்டியில் பிழைகளைக் காட்டு",
    "DESCRIPTION_QUICK_VIEW_ENABLED" : "சரி: விரைவுக் காட்சியை இயக்கு",
    "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW" : "சரி: படத்தைக் காட்டு முடிக்கப்படாத URLகளுக்கான முன்னோட்டங்கள்",
    "DESCRIPTION_THEME" : "{APP_NAME} க்கான தீம் ஒன்றைத் தேர்ந்தெடுக்கவும்",
    "DESCRIPTION_USE_THEME_SCROLLBARS" : "உண்மை: தனிப்பயன் உருள்பட்டிகளை இயக்கு",
    "DESCRIPTION_LINTING_COLLAPSED" : "உண்மை: மதிப்பாய்வுப் பலகத்தைக் குறைக்கு",
    "DESCRIPTION_FONT_FAMILY" : "எழுத்துரு குடும்பத்தை மாற்று",
    "DESCRIPTION_FONT_SIZE" : "எழுத்துரு அளவை மாற்று, எ.கா. 13px",
    "DESCRIPTION_FIND_IN_FILES_NODE" : "உண்மை: முனை அடிப்படையிலான தேடலை இயக்கு",
    "DESCRIPTION_FIND_IN_FILES_INSTANT" : "உண்மை: உடனடி தேடலை இயக்கு",
    "DESCRIPTION_FONT_SMOOTHING" : "Mac மட்டும்: ”subpixel-antialiased” அல்லது ”grayscale antialiasing” மூலம் ”subpixel antialiasing” ஐ இயக்கு",
    "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW" : "false: விருப்பத்தேர்வு கோப்பை பிரிப்புக் காட்சியில் திறப்பதை முடக்கு",
    "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE" : "false: பயனர் விருப்பத்தேர்வுக் கோப்பை இடது அல்லது மேல் பலகத்தில் திறக்கவும்",
    "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED" : "true: பலகத்தில் உள்ள கடைசி கோப்பு பலகத்தின் மேல் உள்ள அடைப்புக்குறியால் மூடப்பட்ட பிறகு பலகங்களை ஒன்றிணைக்கவும்",
    "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS" : "பலகத்தின் மேல் அடைப்புக்குறி மற்றும் புரட்டுக் காட்சி பொத்தான்கள் எப்போது தோன்றும் என்பதைத் தேர்வுசெய்க",
    "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT" : "/*\n * இது {APP_NAME} ஆல் ஆதரிக்கப்படும் விருப்பத்தேர்வுகளின் படிக்க மட்டும் கோப்பு\n * .\n * இதை வழிகாட்டியாகப் பயன்படுத்தும்போது உங்கள் விருப்பத்தேர்வுகள் கோப்பைத் திருத்துதல்\n * “brackets.json”, இது மற்றொரு பலகத்தில் திறக்கப்படும்.\n * {APP_NAME} இல் அமைப்புகளை எவ்வாறு பயன்படுத்துவது என்பது பற்றிய கூடுதல் தகவலுக்கு,\n * https://github.com/brackets-cont/brackets/wiki/How-to-Use-Brackets#preferences\n இல் வலைப்பக்கத்தைப் பார்க்கவும் */",
    "DEFAULT_PREFERENCES_JSON_DEFAULT" : "Default",
    "DESCRIPTION_PURE_CODING_SURFACE" : "true: குறியீடு-மட்டும் பார்வையை இயக்கு மற்றும் {APP_NAME} இல் உள்ள பிற இடைமுக கூறுகளை மறைக்கவும்",
    "DESCRIPTION_INDENT_LINE_COMMENT" : "true: வரி கருத்துகளுக்கு உள்தள்ளலை இயக்கு",
    "DESCRIPTION_RECENT_FILES_NAV" : "சமீபத்திய கோப்புகள் வழிசெலுத்தலை இயக்கு அல்லது முடக்கு",
    "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT" : "முன்னோட்டத்திற்காக WebSocket சேவையகத்தால் பயன்படுத்தப்படும் போர்ட்",
    "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS" : "முன்னோட்ட சிறப்பம்ச அமைப்புகளை"
});
